// Dutch B1/B2 vocabulary. Ranks from OpenSubtitles word-form frequency (hermitdave/FrequencyWords, nl_50k).
// Edit freely: add objects with nl, art, de, pos, cloze, rank. Ids are assigned at load time.
window.WORDS = [{"nl": "volgens","art": null,"de": "laut, gemäß","pos": "bw","cloze": "{Volgens} mij klopt dat niet.","rank": 340,"id": 0},
{"nl": "kans","art": "de","de": "die Chance, die Möglichkeit","pos": "zn","cloze": "De {kans} dat het lukt is klein.","rank": 354,"id": 1},
{"nl": "druk","art": "de","de": "der Druck","pos": "zn","cloze": "Ik voel veel {druk} op mijn werk.","rank": 445,"id": 2},
{"nl": "zorg","art": "de","de": "die Sorge","pos": "zn","cloze": "Dat is mijn grootste {zorg}.","rank": 473,"id": 3},
{"nl": "schuld","art": "de","de": "die Schuld","pos": "zn","cloze": "Het is niet jouw {schuld}.","rank": 482,"id": 4},
{"nl": "meteen","art": null,"de": "sofort","pos": "bw","cloze": "Ik kom er {meteen} aan.","rank": 521,"id": 5},
{"nl": "onderzoek","art": "het","de": "die Untersuchung, die Forschung","pos": "zn","cloze": "Uit {onderzoek} blijkt dat het werkt.","rank": 587,"id": 6},
{"nl": "bewijs","art": "het","de": "der Beweis","pos": "zn","cloze": "Er is geen enkel {bewijs} voor die theorie.","rank": 591,"id": 7},
{"nl": "nogal","art": null,"de": "ziemlich","pos": "bw","cloze": "Dat was {nogal} onhandig.","rank": 663,"id": 8},
{"nl": "zodra","art": null,"de": "sobald","pos": "bw","cloze": "Ik bel je {zodra} ik thuis ben.","rank": 764,"id": 9},
{"nl": "gevaar","art": "het","de": "die Gefahr","pos": "zn","cloze": "Er dreigt {gevaar} bij hoogwater.","rank": 804,"id": 10},
{"nl": "ruimte","art": "de","de": "der Raum, der Platz","pos": "zn","cloze": "Er is nog {ruimte} voor verbetering.","rank": 817,"id": 11},
{"nl": "afspraak","art": "de","de": "die Verabredung, der Termin","pos": "zn","cloze": "Ik heb morgen een {afspraak} bij de tandarts.","rank": 826,"id": 12},
{"nl": "tenzij","art": null,"de": "es sei denn","pos": "bw","cloze": "We gaan door, {tenzij} het gaat onweren.","rank": 831,"id": 13},
{"nl": "bedrijf","art": "het","de": "das Unternehmen","pos": "zn","cloze": "Ze werkt bij een klein {bedrijf}.","rank": 846,"id": 14},
{"nl": "blijkbaar","art": null,"de": "anscheinend","pos": "bw","cloze": "Hij is {blijkbaar} al vertrokken.","rank": 848,"id": 15},
{"nl": "missen","art": null,"de": "vermissen","pos": "ww","cloze": "Ik {mis} mijn oude buurt.","rank": 906,"id": 16},
{"nl": "keuze","art": "de","de": "die Wahl","pos": "zn","cloze": "Dat is een lastige {keuze}.","rank": 928,"id": 17},
{"nl": "regelen","art": null,"de": "regeln, organisieren","pos": "ww","cloze": "Ik {regel} de tickets wel.","rank": 979,"id": 18},
{"nl": "moeite","art": "de","de": "die Mühe","pos": "zn","cloze": "Doe geen {moeite}, ik doe het zelf wel.","rank": 983,"id": 19},
{"nl": "wet","art": "de","de": "das Gesetz","pos": "zn","cloze": "De nieuwe {wet} gaat in januari in.","rank": 999,"id": 20},
{"nl": "uiteindelijk","art": null,"de": "schließlich, letztendlich","pos": "bw","cloze": "{Uiteindelijk} bleven we thuis.","rank": 1016,"id": 21},
{"nl": "lastig","art": null,"de": "schwierig, lästig","pos": "bn","cloze": "Dat wordt een {lastige} klus.","rank": 1029,"id": 22},
{"nl": "bereiken","art": null,"de": "erreichen","pos": "ww","cloze": "We hebben ons doel bijna {bereikt}.","rank": 1102,"id": 23},
{"nl": "haast","art": "de","de": "die Eile","pos": "zn","cloze": "Er is geen {haast} bij.","rank": 1145,"id": 24},
{"nl": "bereid","art": null,"de": "bereit","pos": "bn","cloze": "Ik ben {bereid} om te helpen.","rank": 1220,"id": 25},
{"nl": "verschil","art": "het","de": "der Unterschied","pos": "zn","cloze": "Het {verschil} is nauwelijks te zien.","rank": 1224,"id": 26},
{"nl": "rekening","art": "de","de": "die Rechnung","pos": "zn","cloze": "Mag ik de {rekening}, alstublieft?","rank": 1231,"id": 27},
{"nl": "richting","art": "de","de": "die Richtung","pos": "zn","cloze": "We liepen in de verkeerde {richting}.","rank": 1256,"id": 28},
{"nl": "indruk","art": "de","de": "der Eindruck","pos": "zn","cloze": "Ik had de {indruk} dat ze moe was.","rank": 1279,"id": 29},
{"nl": "last","art": "de","de": "die Last","pos": "zn","cloze": "Ik heb {last} van mijn rug.","rank": 1289,"id": 30},
{"nl": "kennis","art": "de","de": "das Wissen","pos": "zn","cloze": "Mijn {kennis} van het Nederlands wordt beter.","rank": 1294,"id": 31},
{"nl": "ervaring","art": "de","de": "die Erfahrung","pos": "zn","cloze": "Ze heeft jarenlange {ervaring} in de zorg.","rank": 1359,"id": 32},
{"nl": "leeftijd","art": "de","de": "das Alter","pos": "zn","cloze": "Op die {leeftijd} leer je snel.","rank": 1372,"id": 33},
{"nl": "toevallig","art": null,"de": "zufällig","pos": "bn","cloze": "Ik kwam haar {toevallig} tegen.","rank": 1423,"id": 34},
{"nl": "verbergen","art": null,"de": "verbergen","pos": "ww","cloze": "Ze kon haar teleurstelling niet {verbergen}.","rank": 1432,"id": 35},
{"nl": "behoorlijk","art": null,"de": "ziemlich, ordentlich","pos": "bn","cloze": "Het was {behoorlijk} koud vanochtend.","rank": 1443,"id": 36},
{"nl": "voorkomen","art": null,"de": "verhindern","pos": "ww","cloze": "Zo kun je veel problemen {voorkomen}.","rank": 1512,"id": 37},
{"nl": "mening","art": "de","de": "die Meinung","pos": "zn","cloze": "Naar mijn {mening} is dat te duur.","rank": 1518,"id": 38},
{"nl": "oplossen","art": null,"de": "lösen","pos": "ww","cloze": "We moeten dit probleem samen {oplossen}.","rank": 1529,"id": 39},
{"nl": "onmiddellijk","art": null,"de": "sofort","pos": "bw","cloze": "Ze reageerde {onmiddellijk}.","rank": 1533,"id": 40},
{"nl": "gedrag","art": "het","de": "das Verhalten","pos": "zn","cloze": "Zijn {gedrag} was echt onacceptabel.","rank": 1534,"id": 41},
{"nl": "verband","art": "het","de": "der Zusammenhang","pos": "zn","cloze": "Er is geen {verband} tussen die twee dingen.","rank": 1566,"id": 42},
{"nl": "steun","art": "de","de": "die Unterstützung","pos": "zn","cloze": "Bedankt voor je {steun}.","rank": 1660,"id": 43},
{"nl": "oplossing","art": "de","de": "die Lösung","pos": "zn","cloze": "Er is nog geen {oplossing} gevonden.","rank": 1670,"id": 44},
{"nl": "wellicht","art": null,"de": "vielleicht","pos": "bw","cloze": "{Wellicht} kunnen we het later bespreken.","rank": 1674,"id": 45},
{"nl": "nauwelijks","art": null,"de": "kaum","pos": "bw","cloze": "Ik kon hem {nauwelijks} verstaan.","rank": 1680,"id": 46},
{"nl": "verwachten","art": null,"de": "erwarten","pos": "ww","cloze": "Ik had er meer van {verwacht}.","rank": 1725,"id": 47},
{"nl": "ondanks","art": null,"de": "trotz","pos": "bw","cloze": "{Ondanks} de regen was het gezellig.","rank": 1760,"id": 48},
{"nl": "tevreden","art": null,"de": "zufrieden","pos": "bn","cloze": "Ik ben heel {tevreden} met het resultaat.","rank": 1794,"id": 49},
{"nl": "belang","art": "het","de": "die Bedeutung, das Interesse","pos": "zn","cloze": "Het is van groot {belang} dat je op tijd komt.","rank": 1809,"id": 50},
{"nl": "lukken","art": null,"de": "gelingen","pos": "ww","cloze": "Het is me eindelijk {gelukt}.","rank": 1811,"id": 51},
{"nl": "gedragen","art": null,"de": "sich benehmen","pos": "ww","cloze": "{Gedraag} je een beetje.","rank": 1819,"id": 52},
{"nl": "toeval","art": "het","de": "der Zufall","pos": "zn","cloze": "Dat is puur {toeval}.","rank": 1851,"id": 53},
{"nl": "genieten","art": null,"de": "genießen","pos": "ww","cloze": "We hebben enorm {genoten} van de vakantie.","rank": 1861,"id": 54},
{"nl": "ruim","art": null,"de": "geräumig, reichlich","pos": "bn","cloze": "We hebben nog {ruim} de tijd.","rank": 1882,"id": 55},
{"nl": "kwestie","art": "de","de": "die Angelegenheit, die Frage","pos": "zn","cloze": "Dat is een {kwestie} van smaak.","rank": 1891,"id": 56},
{"nl": "omgeving","art": "de","de": "die Umgebung","pos": "zn","cloze": "De {omgeving} is heel rustig.","rank": 1895,"id": 57},
{"nl": "aanbod","art": "het","de": "das Angebot","pos": "zn","cloze": "Het {aanbod} geldt tot het einde van de maand.","rank": 1902,"id": 58},
{"nl": "opgeven","art": null,"de": "aufgeben","pos": "ww","cloze": "Geef nooit te snel {op}.","rank": 1945,"id": 59},
{"nl": "invloed","art": "de","de": "der Einfluss","pos": "zn","cloze": "Zijn mening heeft veel {invloed} op de groep.","rank": 1981,"id": 60},
{"nl": "verantwoordelijkheid","art": "de","de": "die Verantwortung","pos": "zn","cloze": "Hij neemt zijn {verantwoordelijkheid} serieus.","rank": 1986,"id": 61},
{"nl": "overtuigen","art": null,"de": "überzeugen","pos": "ww","cloze": "Zijn argumenten hebben me niet {overtuigd}.","rank": 2022,"id": 62},
{"nl": "toegeven","art": null,"de": "zugeben","pos": "ww","cloze": "Hij wilde niet {toegeven} dat hij fout zat.","rank": 2025,"id": 63},
{"nl": "vervelend","art": null,"de": "lästig, langweilig","pos": "bn","cloze": "Wat {vervelend} voor je.","rank": 2048,"id": 64},
{"nl": "gewend","art": null,"de": "gewohnt","pos": "bn","cloze": "Ik ben dat niet {gewend}.","rank": 2060,"id": 65},
{"nl": "verhuizen","art": null,"de": "umziehen","pos": "ww","cloze": "We {verhuizen} volgende maand naar Utrecht.","rank": 2081,"id": 66},
{"nl": "waarde","art": "de","de": "der Wert","pos": "zn","cloze": "Dat heeft voor mij veel {waarde}.","rank": 2082,"id": 67},
{"nl": "overheid","art": "de","de": "die Regierung, der Staat","pos": "zn","cloze": "De {overheid} betaalt een deel mee.","rank": 2093,"id": 68},
{"nl": "uiteraard","art": null,"de": "selbstverständlich","pos": "bw","cloze": "Dat mag {uiteraard}.","rank": 2097,"id": 69},
{"nl": "amper","art": null,"de": "kaum","pos": "bw","cloze": "Ik heb {amper} geslapen.","rank": 2104,"id": 70},
{"nl": "poging","art": "de","de": "der Versuch","pos": "zn","cloze": "Bij de derde {poging} lukte het.","rank": 2111,"id": 71},
{"nl": "voordeel","art": "het","de": "der Vorteil","pos": "zn","cloze": "Dat heeft ook een groot {voordeel}.","rank": 2133,"id": 72},
{"nl": "voorlopig","art": null,"de": "vorläufig","pos": "bn","cloze": "{Voorlopig} blijft alles zoals het is.","rank": 2218,"id": 73},
{"nl": "zwijgen","art": null,"de": "schweigen","pos": "ww","cloze": "Ze bleef de hele avond {zwijgen}.","rank": 2290,"id": 74},
{"nl": "minstens","art": null,"de": "mindestens","pos": "bw","cloze": "Je moet {minstens} twee uur wachten.","rank": 2338,"id": 75},
{"nl": "wijze","art": "de","de": "die Art und Weise","pos": "zn","cloze": "Op welke {wijze} wilt u betalen?","rank": 2345,"id": 76},
{"nl": "toestand","art": "de","de": "der Zustand","pos": "zn","cloze": "De {toestand} van de patiënt is stabiel.","rank": 2401,"id": 77},
{"nl": "bovendien","art": null,"de": "außerdem","pos": "bw","cloze": "Het is duur, en {bovendien} lelijk.","rank": 2406,"id": 78},
{"nl": "bewaren","art": null,"de": "aufbewahren","pos": "ww","cloze": "{Bewaar} de kaassoorten in de koelkast.","rank": 2408,"id": 79},
{"nl": "bezwaar","art": "het","de": "der Einwand","pos": "zn","cloze": "Heb je {bezwaar} als ik het raam opendoe?","rank": 2426,"id": 80},
{"nl": "bevestigen","art": null,"de": "bestätigen","pos": "ww","cloze": "Kunt u de afspraak per mail {bevestigen}?","rank": 2427,"id": 81},
{"nl": "voldoende","art": null,"de": "ausreichend","pos": "bn","cloze": "Er is {voldoende} eten voor iedereen.","rank": 2467,"id": 82},
{"nl": "redelijk","art": null,"de": "ziemlich, vernünftig","pos": "bn","cloze": "Het gaat {redelijk} goed.","rank": 2474,"id": 83},
{"nl": "onderwerp","art": "het","de": "das Thema","pos": "zn","cloze": "Laten we van {onderwerp} veranderen.","rank": 2481,"id": 84},
{"nl": "bewust","art": null,"de": "bewusst","pos": "bn","cloze": "Ik was me daar niet van {bewust}.","rank": 2484,"id": 85},
{"nl": "plotseling","art": null,"de": "plötzlich","pos": "bn","cloze": "{Plotseling} ging het licht uit.","rank": 2569,"id": 86},
{"nl": "ingewikkeld","art": null,"de": "kompliziert","pos": "bn","cloze": "Dat is te {ingewikkeld} om nu uit te leggen.","rank": 2573,"id": 87},
{"nl": "besef","art": "het","de": "das Bewusstsein","pos": "zn","cloze": "Het {besef} kwam pas veel later.","rank": 2576,"id": 88},
{"nl": "ontslaan","art": null,"de": "entlassen","pos": "ww","cloze": "Ze is vorige maand {ontslagen}.","rank": 2635,"id": 89},
{"nl": "klagen","art": null,"de": "klagen, sich beschweren","pos": "ww","cloze": "Ze {klaagt} altijd over het weer.","rank": 2675,"id": 90},
{"nl": "dringend","art": null,"de": "dringend","pos": "bn","cloze": "Ik moet je {dringend} spreken.","rank": 2679,"id": 91},
{"nl": "eisen","art": null,"de": "fordern, verlangen","pos": "ww","cloze": "De vakbond {eist} hogere lonen.","rank": 2681,"id": 92},
{"nl": "geschikt","art": null,"de": "geeignet","pos": "bn","cloze": "Deze film is niet {geschikt} voor kinderen.","rank": 2748,"id": 93},
{"nl": "storen","art": null,"de": "stören","pos": "ww","cloze": "Sorry dat ik {stoor}.","rank": 2756,"id": 94},
{"nl": "dwingen","art": null,"de": "zwingen","pos": "ww","cloze": "Niemand kan je {dwingen} om te tekenen.","rank": 2758,"id": 95},
{"nl": "namelijk","art": null,"de": "nämlich","pos": "bw","cloze": "Ik kan niet komen; ik ben {namelijk} ziek.","rank": 2799,"id": 96},
{"nl": "negeren","art": null,"de": "ignorieren","pos": "ww","cloze": "Hij {negeerde} mijn vraag volledig.","rank": 2811,"id": 97},
{"nl": "beschikbaar","art": null,"de": "verfügbar","pos": "bn","cloze": "Het rapport is nu online {beschikbaar}.","rank": 2874,"id": 98},
{"nl": "gevoelig","art": null,"de": "empfindlich, sensibel","pos": "bn","cloze": "Dat is een {gevoelig} onderwerp.","rank": 2890,"id": 99},
{"nl": "middel","art": "het","de": "das Mittel","pos": "zn","cloze": "Dat is een effectief {middel} tegen jeuk.","rank": 2921,"id": 100},
{"nl": "veroorzaken","art": null,"de": "verursachen","pos": "ww","cloze": "De storm heeft veel schade {veroorzaakt}.","rank": 2929,"id": 101},
{"nl": "herkennen","art": null,"de": "wiedererkennen","pos": "ww","cloze": "Ik {herkende} haar stem meteen.","rank": 3040,"id": 102},
{"nl": "behoefte","art": "de","de": "das Bedürfnis","pos": "zn","cloze": "Er is grote {behoefte} aan betaalbare woningen.","rank": 3043,"id": 103},
{"nl": "oorzaak","art": "de","de": "die Ursache","pos": "zn","cloze": "De {oorzaak} van de brand is nog onbekend.","rank": 3044,"id": 104},
{"nl": "uitdaging","art": "de","de": "die Herausforderung","pos": "zn","cloze": "Dit project is een echte {uitdaging}.","rank": 3065,"id": 105},
{"nl": "onderhandelen","art": null,"de": "verhandeln","pos": "ww","cloze": "We {onderhandelen} nog over de prijs.","rank": 3066,"id": 106},
{"nl": "slagen","art": null,"de": "bestehen, gelingen","pos": "ww","cloze": "Ze is voor haar examen {geslaagd}.","rank": 3070,"id": 107},
{"nl": "waarderen","art": null,"de": "schätzen, würdigen","pos": "ww","cloze": "Ik {waardeer} je eerlijkheid.","rank": 3118,"id": 108},
{"nl": "ontstaan","art": null,"de": "entstehen","pos": "ww","cloze": "Hoe is die gewoonte eigenlijk {ontstaan}?","rank": 3141,"id": 109},
{"nl": "kennelijk","art": null,"de": "offenbar","pos": "bw","cloze": "Ze had het {kennelijk} niet gelezen.","rank": 3142,"id": 110},
{"nl": "vooruitgang","art": "de","de": "der Fortschritt","pos": "zn","cloze": "Je maakt duidelijk {vooruitgang}.","rank": 3175,"id": 111},
{"nl": "verzinnen","art": null,"de": "sich ausdenken","pos": "ww","cloze": "Hij kan altijd wel een smoes {verzinnen}.","rank": 3195,"id": 112},
{"nl": "vermogen","art": "het","de": "die Fähigkeit, das Vermögen","pos": "zn","cloze": "Ze heeft een groot {vermogen} om te luisteren.","rank": 3202,"id": 113},
{"nl": "telkens","art": null,"de": "jedes Mal","pos": "bw","cloze": "Hij vergeet het {telkens} weer.","rank": 3209,"id": 114},
{"nl": "achtergrond","art": "de","de": "der Hintergrund","pos": "zn","cloze": "Wat is jouw {achtergrond} qua opleiding?","rank": 3290,"id": 115},
{"nl": "daad","art": "de","de": "die Tat","pos": "zn","cloze": "Het was een moedige {daad}.","rank": 3320,"id": 116},
{"nl": "verplicht","art": null,"de": "verpflichtet, Pflicht-","pos": "bn","cloze": "Een helm is hier {verplicht}.","rank": 3355,"id": 117},
{"nl": "gebrek","art": "het","de": "der Mangel","pos": "zn","cloze": "Door {gebrek} aan tijd is het niet gelukt.","rank": 3371,"id": 118},
{"nl": "ervaren","art": null,"de": "erfahren, erleben","pos": "ww","cloze": "Ik heb dat zelf ook zo {ervaren}.","rank": 3432,"id": 119},
{"nl": "verspillen","art": null,"de": "verschwenden","pos": "ww","cloze": "Laten we geen tijd {verspillen}.","rank": 3446,"id": 120},
{"nl": "weigeren","art": null,"de": "sich weigern, verweigern","pos": "ww","cloze": "Hij {weigerde} zijn excuses aan te bieden.","rank": 3476,"id": 121},
{"nl": "opzet","art": "de","de": "die Absicht","pos": "zn","cloze": "Dat deed hij met {opzet}.","rank": 3491,"id": 122},
{"nl": "nuttig","art": null,"de": "nützlich","pos": "bn","cloze": "Dat was een {nuttige} tip.","rank": 3535,"id": 123},
{"nl": "gevolg","art": "het","de": "die Folge","pos": "zn","cloze": "Dat had grote {gevolgen} voor het bedrijf.","rank": 3561,"id": 124},
{"nl": "wennen","art": null,"de": "sich gewöhnen","pos": "ww","cloze": "Je moet even {wennen} aan het toetsenbord.","rank": 3582,"id": 125},
{"nl": "gemak","art": "het","de": "die Bequemlichkeit, die Leichtigkeit","pos": "zn","cloze": "Hij deed het met veel {gemak}.","rank": 3602,"id": 126},
{"nl": "vermijden","art": null,"de": "vermeiden","pos": "ww","cloze": "Probeer de spits te {vermijden}.","rank": 3625,"id": 127},
{"nl": "ontkennen","art": null,"de": "leugnen, abstreiten","pos": "ww","cloze": "Hij blijft alles {ontkennen}.","rank": 3669,"id": 128},
{"nl": "benieuwd","art": null,"de": "gespannt, neugierig","pos": "bn","cloze": "Ik ben {benieuwd} wat ze ervan vindt.","rank": 3685,"id": 129},
{"nl": "stiekem","art": null,"de": "heimlich","pos": "bw","cloze": "Hij keek {stiekem} op zijn telefoon.","rank": 3731,"id": 130},
{"nl": "overwegen","art": null,"de": "erwägen, in Betracht ziehen","pos": "ww","cloze": "Ik {overweeg} om te verhuizen.","rank": 3833,"id": 131},
{"nl": "afhankelijk","art": null,"de": "abhängig","pos": "bn","cloze": "Dat is {afhankelijk} van het weer.","rank": 3836,"id": 132},
{"nl": "afspreken","art": null,"de": "vereinbaren, ausmachen","pos": "ww","cloze": "Zullen we iets {afspreken} voor volgende week?","rank": 3885,"id": 133},
{"nl": "vermoeden","art": null,"de": "vermuten","pos": "ww","cloze": "Ik {vermoed} dat ze het al weet.","rank": 3894,"id": 134},
{"nl": "begrip","art": "het","de": "das Verständnis","pos": "zn","cloze": "Dank je voor je {begrip}.","rank": 3911,"id": 135},
{"nl": "gewoonte","art": "de","de": "die Gewohnheit","pos": "zn","cloze": "Het is een oude {gewoonte} van me.","rank": 3925,"id": 136},
{"nl": "klacht","art": "de","de": "die Beschwerde","pos": "zn","cloze": "Er zijn veel {klachten} binnengekomen.","rank": 3988,"id": 137},
{"nl": "verwerken","art": null,"de": "verarbeiten","pos": "ww","cloze": "Ze moet het nieuws nog {verwerken}.","rank": 3996,"id": 138},
{"nl": "regelmatig","art": null,"de": "regelmäßig","pos": "bn","cloze": "Ik ga {regelmatig} zwemmen.","rank": 4069,"id": 139},
{"nl": "herhalen","art": null,"de": "wiederholen","pos": "ww","cloze": "Kun je dat nog een keer {herhalen}?","rank": 4130,"id": 140},
{"nl": "doorstaan","art": null,"de": "überstehen, durchstehen","pos": "ww","cloze": "De brug heeft de storm goed {doorstaan}.","rank": 4220,"id": 141},
{"nl": "achterhalen","art": null,"de": "herausfinden, ermitteln","pos": "ww","cloze": "De politie probeert de dader te {achterhalen}.","rank": 4240,"id": 142},
{"nl": "verrassen","art": null,"de": "überraschen","pos": "ww","cloze": "Dat antwoord {verraste} me.","rank": 4253,"id": 143},
{"nl": "bevolking","art": "de","de": "die Bevölkerung","pos": "zn","cloze": "De {bevolking} van de stad groeit snel.","rank": 4260,"id": 144},
{"nl": "voortaan","art": null,"de": "künftig, von nun an","pos": "bw","cloze": "{Voortaan} doe ik het zelf.","rank": 4269,"id": 145},
{"nl": "zeldzaam","art": null,"de": "selten","pos": "bn","cloze": "Die vogel is heel {zeldzaam} geworden.","rank": 4333,"id": 146},
{"nl": "beseffen","art": null,"de": "begreifen, sich bewusst werden","pos": "ww","cloze": "Ik {besefte} pas later hoe erg het was.","rank": 4400,"id": 147},
{"nl": "noodzakelijk","art": null,"de": "notwendig","pos": "bn","cloze": "Een visum is niet {noodzakelijk}.","rank": 4413,"id": 148},
{"nl": "afnemen","art": null,"de": "abnehmen","pos": "ww","cloze": "De belangstelling {neemt} langzaam {af}.","rank": 4478,"id": 149},
{"nl": "vrijwel","art": null,"de": "so gut wie, nahezu","pos": "bw","cloze": "Het is {vrijwel} onmogelijk.","rank": 4525,"id": 150},
{"nl": "zeuren","art": null,"de": "nörgeln, quengeln","pos": "ww","cloze": "Hou eens op met {zeuren}.","rank": 4619,"id": 151},
{"nl": "uitzondering","art": "de","de": "die Ausnahme","pos": "zn","cloze": "Er is één belangrijke {uitzondering}.","rank": 4705,"id": 152},
{"nl": "eis","art": "de","de": "die Forderung","pos": "zn","cloze": "Aan die {eis} kunnen we niet voldoen.","rank": 4750,"id": 153},
{"nl": "grondig","art": null,"de": "gründlich","pos": "bn","cloze": "We hebben alles {grondig} gecontroleerd.","rank": 4765,"id": 154},
{"nl": "aanvaarden","art": null,"de": "annehmen, akzeptieren","pos": "ww","cloze": "Ze heeft de baan uiteindelijk {aanvaard}.","rank": 4768,"id": 155},
{"nl": "belasting","art": "de","de": "die Steuer","pos": "zn","cloze": "Over dat inkomen betaal je {belasting}.","rank": 4814,"id": 156},
{"nl": "beweren","art": null,"de": "behaupten","pos": "ww","cloze": "Hij {beweert} dat hij van niets wist.","rank": 4912,"id": 157},
{"nl": "voorwaarde","art": "de","de": "die Bedingung","pos": "zn","cloze": "Ik doe het, op één {voorwaarde}.","rank": 5031,"id": 158},
{"nl": "aanpak","art": "de","de": "die Herangehensweise, der Ansatz","pos": "zn","cloze": "Ik ben het niet eens met deze {aanpak}.","rank": 5096,"id": 159},
{"nl": "samenleving","art": "de","de": "die Gesellschaft","pos": "zn","cloze": "De {samenleving} verandert snel.","rank": 5394,"id": 160},
{"nl": "betrouwbaar","art": null,"de": "zuverlässig","pos": "bn","cloze": "Is die bron wel {betrouwbaar}?","rank": 5401,"id": 161},
{"nl": "schatten","art": null,"de": "schätzen","pos": "ww","cloze": "Ik {schat} hem op een jaar of veertig.","rank": 5488,"id": 162},
{"nl": "sfeer","art": "de","de": "die Stimmung, die Atmosphäre","pos": "zn","cloze": "Er hing een gespannen {sfeer}.","rank": 5725,"id": 163},
{"nl": "ondergaan","art": null,"de": "über sich ergehen lassen","pos": "ww","cloze": "Ze moest een zware operatie {ondergaan}.","rank": 5814,"id": 164},
{"nl": "inmiddels","art": null,"de": "inzwischen","pos": "bw","cloze": "Ze woont hier {inmiddels} vijf jaar.","rank": 5879,"id": 165},
{"nl": "onverwacht","art": null,"de": "unerwartet","pos": "bn","cloze": "Het bezoek kwam volledig {onverwacht}.","rank": 5998,"id": 166},
{"nl": "althans","art": null,"de": "zumindest","pos": "bw","cloze": "Hij komt, {althans} dat zei hij.","rank": 6055,"id": 167},
{"nl": "destijds","art": null,"de": "damals","pos": "bw","cloze": "Dat was {destijds} heel normaal.","rank": 6140,"id": 168},
{"nl": "voorheen","art": null,"de": "früher, vormals","pos": "bw","cloze": "Dit heette {voorheen} anders.","rank": 6164,"id": 169},
{"nl": "blijken","art": null,"de": "sich herausstellen","pos": "ww","cloze": "Het {bleek} achteraf een misverstand te zijn.","rank": 6383,"id": 170},
{"nl": "uitstellen","art": null,"de": "aufschieben, verschieben","pos": "ww","cloze": "Kunnen we de vergadering {uitstellen}?","rank": 6428,"id": 171},
{"nl": "haasten","art": null,"de": "sich beeilen","pos": "ww","cloze": "Je hoeft je niet te {haasten}.","rank": 6621,"id": 172},
{"nl": "onderscheiden","art": null,"de": "unterscheiden","pos": "ww","cloze": "Je moet feiten van meningen {onderscheiden}.","rank": 6664,"id": 173},
{"nl": "deels","art": null,"de": "teilweise","pos": "bw","cloze": "Dat klopt {deels}.","rank": 6800,"id": 174},
{"nl": "overleg","art": "het","de": "die Absprache, die Beratung","pos": "zn","cloze": "Na {overleg} met mijn collega's besloot ik te blijven.","rank": 6804,"id": 175},
{"nl": "ondernemen","art": null,"de": "unternehmen","pos": "ww","cloze": "Er moet snel actie worden {ondernomen}.","rank": 6848,"id": 176},
{"nl": "bijdrage","art": "de","de": "der Beitrag","pos": "zn","cloze": "Bedankt voor je waardevolle {bijdrage}.","rank": 6858,"id": 177},
{"nl": "begrijpelijk","art": null,"de": "verständlich","pos": "bn","cloze": "Je reactie is heel {begrijpelijk}.","rank": 7222,"id": 178},
{"nl": "zorgvuldig","art": null,"de": "sorgfältig","pos": "bn","cloze": "Lees de voorwaarden {zorgvuldig} door.","rank": 7269,"id": 179},
{"nl": "uitgebreid","art": null,"de": "ausführlich, umfangreich","pos": "bn","cloze": "Hij gaf een {uitgebreide} uitleg.","rank": 7419,"id": 180},
{"nl": "nauwkeurig","art": null,"de": "genau, präzise","pos": "bn","cloze": "Meet het zo {nauwkeurig} mogelijk.","rank": 7589,"id": 181},
{"nl": "beschouwen","art": null,"de": "betrachten, ansehen als","pos": "ww","cloze": "Ik {beschouw} hem als een goede vriend.","rank": 7593,"id": 182},
{"nl": "overdrijven","art": null,"de": "übertreiben","pos": "ww","cloze": "Nu {overdrijf} je echt.","rank": 7647,"id": 183},
{"nl": "overigens","art": null,"de": "übrigens","pos": "bw","cloze": "{Overigens} heb ik dat nooit gezegd.","rank": 7697,"id": 184},
{"nl": "vanzelfsprekend","art": null,"de": "selbstverständlich","pos": "bn","cloze": "Dat is helemaal niet {vanzelfsprekend}.","rank": 7698,"id": 185},
{"nl": "verwachting","art": "de","de": "die Erwartung","pos": "zn","cloze": "Het resultaat overtrof onze {verwachtingen}.","rank": 7728,"id": 186},
{"nl": "enigszins","art": null,"de": "einigermaßen","pos": "bw","cloze": "Ik ben {enigszins} verbaasd.","rank": 7778,"id": 187},
{"nl": "neiging","art": "de","de": "die Neigung","pos": "zn","cloze": "Ik heb de {neiging} om alles uit te stellen.","rank": 8006,"id": 188},
{"nl": "somber","art": null,"de": "düster, trübe","pos": "bn","cloze": "Ze is de laatste tijd nogal {somber}.","rank": 8215,"id": 189},
{"nl": "alsnog","art": null,"de": "doch noch","pos": "bw","cloze": "Het is {alsnog} gelukt.","rank": 8481,"id": 190},
{"nl": "vaststellen","art": null,"de": "feststellen","pos": "ww","cloze": "De arts {stelde} een lichte ontsteking {vast}.","rank": 8504,"id": 191},
{"nl": "opvallen","art": null,"de": "auffallen","pos": "ww","cloze": "Het {viel} me {op} dat hij stiller was dan anders.","rank": 8740,"id": 192},
{"nl": "handhaven","art": null,"de": "aufrechterhalten, durchsetzen","pos": "ww","cloze": "De gemeente wil de regels strenger {handhaven}.","rank": 9079,"id": 193},
{"nl": "gebruikelijk","art": null,"de": "üblich","pos": "bn","cloze": "Dat is hier niet {gebruikelijk}.","rank": 9104,"id": 194},
{"nl": "ontbreken","art": null,"de": "fehlen","pos": "ww","cloze": "Er {ontbreekt} nog een handtekening.","rank": 9230,"id": 195},
{"nl": "vaardigheid","art": "de","de": "die Fertigkeit","pos": "zn","cloze": "Dat is een {vaardigheid} die je kunt leren.","rank": 9264,"id": 196},
{"nl": "tamelijk","art": null,"de": "ziemlich","pos": "bw","cloze": "Het is een {tamelijk} lang boek.","rank": 9417,"id": 197},
{"nl": "inspanning","art": "de","de": "die Anstrengung","pos": "zn","cloze": "Het kostte veel {inspanning}.","rank": 9557,"id": 198},
{"nl": "overbodig","art": null,"de": "überflüssig","pos": "bn","cloze": "Die stap is eigenlijk {overbodig}.","rank": 9570,"id": 199},
{"nl": "streven","art": null,"de": "streben","pos": "ww","cloze": "We {streven} naar een oplossing voor het einde van het jaar.","rank": 9725,"id": 200},
{"nl": "daarentegen","art": null,"de": "hingegen, dagegen","pos": "bw","cloze": "Zijn broer is {daarentegen} heel rustig.","rank": 9731,"id": 201},
{"nl": "bijdragen","art": null,"de": "beitragen","pos": "ww","cloze": "Iedereen kan iets {bijdragen} aan het project.","rank": 9783,"id": 202},
{"nl": "mislukken","art": null,"de": "scheitern","pos": "ww","cloze": "Het eerste experiment is {mislukt}.","rank": 9944,"id": 203},
{"nl": "nadeel","art": "het","de": "der Nachteil","pos": "zn","cloze": "Het enige {nadeel} is de prijs.","rank": 10125,"id": 204},
{"nl": "aandringen","art": null,"de": "drängen, darauf bestehen","pos": "ww","cloze": "Hij bleef {aandringen} op een verklaring.","rank": 10251,"id": 205},
{"nl": "afwijzen","art": null,"de": "ablehnen","pos": "ww","cloze": "De bank heeft mijn aanvraag {afgewezen}.","rank": 10338,"id": 206},
{"nl": "tevens","art": null,"de": "zugleich, außerdem","pos": "bw","cloze": "Hij is arts en {tevens} onderzoeker.","rank": 10373,"id": 207},
{"nl": "opvallend","art": null,"de": "auffällig","pos": "bn","cloze": "Het is {opvallend} hoe stil het is.","rank": 10416,"id": 208},
{"nl": "inleveren","art": null,"de": "abgeben","pos": "ww","cloze": "Je moet het formulier vrijdag {inleveren}.","rank": 10504,"id": 209},
{"nl": "grotendeels","art": null,"de": "größtenteils","pos": "bw","cloze": "Het werk is {grotendeels} klaar.","rank": 10550,"id": 210},
{"nl": "vergissen","art": null,"de": "sich irren","pos": "ww","cloze": "Ik heb me in hem {vergist}.","rank": 10556,"id": 211},
{"nl": "aanzienlijk","art": null,"de": "beträchtlich, erheblich","pos": "bn","cloze": "De prijs is {aanzienlijk} gestegen.","rank": 11070,"id": 212},
{"nl": "eigenschap","art": "de","de": "die Eigenschaft","pos": "zn","cloze": "Geduld is een handige {eigenschap}.","rank": 11465,"id": 213},
{"nl": "stelling","art": "de","de": "die These","pos": "zn","cloze": "Ik ben het niet eens met die {stelling}.","rank": 11814,"id": 214},
{"nl": "gunnen","art": null,"de": "gönnen","pos": "ww","cloze": "Ik {gun} het je van harte.","rank": 11844,"id": 215},
{"nl": "aanmoedigen","art": null,"de": "ermutigen","pos": "ww","cloze": "Mijn ouders {moedigden} me altijd {aan} om door te zetten.","rank": 12087,"id": 216},
{"nl": "aarzelen","art": null,"de": "zögern","pos": "ww","cloze": "Ik {aarzelde} even voordat ik antwoordde.","rank": 12213,"id": 217},
{"nl": "merkwaardig","art": null,"de": "merkwürdig","pos": "bn","cloze": "Ik vond zijn reactie nogal {merkwaardig}.","rank": 12454,"id": 218},
{"nl": "zinvol","art": null,"de": "sinnvoll","pos": "bn","cloze": "Is het wel {zinvol} om door te gaan?","rank": 12533,"id": 219},
{"nl": "hoogstens","art": null,"de": "höchstens","pos": "bw","cloze": "Het duurt {hoogstens} tien minuten.","rank": 12569,"id": 220},
{"nl": "drempel","art": "de","de": "die Schwelle","pos": "zn","cloze": "De {drempel} om hulp te vragen is hoog.","rank": 12778,"id": 221},
{"nl": "opmerken","art": null,"de": "bemerken","pos": "ww","cloze": "Ze {merkte} droogjes {op} dat het al laat was.","rank": 13272,"id": 222},
{"nl": "geleidelijk","art": null,"de": "allmählich","pos": "bn","cloze": "Het gaat {geleidelijk} beter.","rank": 13296,"id": 223},
{"nl": "mits","art": null,"de": "sofern, vorausgesetzt","pos": "bw","cloze": "Het kan, {mits} je op tijd reserveert.","rank": 13314,"id": 224},
{"nl": "afkeer","art": "de","de": "die Abneigung","pos": "zn","cloze": "Ik heb een diepe {afkeer} van bureaucratie.","rank": 13511,"id": 225},
{"nl": "nadruk","art": "de","de": "die Betonung","pos": "zn","cloze": "De {nadruk} ligt op de eerste lettergreep.","rank": 13523,"id": 226},
{"nl": "schaars","art": null,"de": "knapp, rar","pos": "bn","cloze": "Water werd steeds {schaarser}.","rank": 13648,"id": 227},
{"nl": "beschikken","art": null,"de": "verfügen über","pos": "ww","cloze": "Het huis {beschikt} over een grote tuin.","rank": 13808,"id": 228},
{"nl": "desondanks","art": null,"de": "dennoch, trotzdem","pos": "bw","cloze": "Het regende; {desondanks} gingen we op pad.","rank": 14008,"id": 229},
{"nl": "gemeenschappelijk","art": null,"de": "gemeinsam","pos": "bn","cloze": "We hebben een {gemeenschappelijk} doel.","rank": 14108,"id": 230},
{"nl": "benadrukken","art": null,"de": "betonen","pos": "ww","cloze": "De arts {benadrukte} dat rust belangrijk is.","rank": 14405,"id": 231},
{"nl": "struikelen","art": null,"de": "stolpern","pos": "ww","cloze": "Ik {struikelde} over een losse stoeptegel.","rank": 16176,"id": 232},
{"nl": "meevallen","art": null,"de": "besser ausfallen als erwartet","pos": "ww","cloze": "Gelukkig {viel} de rekening {mee}.","rank": 16179,"id": 233},
{"nl": "nalaten","art": null,"de": "unterlassen","pos": "ww","cloze": "Hij kon niet {nalaten} er iets over te zeggen.","rank": 16403,"id": 234},
{"nl": "bevorderen","art": null,"de": "fördern","pos": "ww","cloze": "Sporten {bevordert} de gezondheid.","rank": 16639,"id": 235},
{"nl": "belemmeren","art": null,"de": "behindern","pos": "ww","cloze": "De regels {belemmeren} kleine bedrijven.","rank": 16918,"id": 236},
{"nl": "bewering","art": "de","de": "die Behauptung","pos": "zn","cloze": "Die {bewering} klopt niet.","rank": 17270,"id": 237},
{"nl": "ergeren","art": null,"de": "sich ärgern","pos": "ww","cloze": "Ik {erger} me aan dat geluid.","rank": 17600,"id": 238},
{"nl": "toename","art": "de","de": "die Zunahme","pos": "zn","cloze": "We zien een {toename} van het aantal aanvragen.","rank": 18221,"id": 239},
{"nl": "weliswaar","art": null,"de": "zwar","pos": "bw","cloze": "Het is {weliswaar} laat, maar ik kom nog.","rank": 18803,"id": 240},
{"nl": "toenemen","art": null,"de": "zunehmen","pos": "ww","cloze": "Het aantal klachten is sterk {toegenomen}.","rank": 18870,"id": 241},
{"nl": "verduidelijken","art": null,"de": "verdeutlichen","pos": "ww","cloze": "Kun je dat punt nog even {verduidelijken}?","rank": 19968,"id": 242},
{"nl": "maatregel","art": "de","de": "die Maßnahme","pos": "zn","cloze": "De regering neemt strenge {maatregelen}.","rank": 21707,"id": 243},
{"nl": "opvatting","art": "de","de": "die Auffassung","pos": "zn","cloze": "Zijn {opvatting} is behoorlijk ouderwets.","rank": 21884,"id": 244},
{"nl": "omstandigheid","art": "de","de": "der Umstand","pos": "zn","cloze": "Onder deze {omstandigheden} gaat het niet.","rank": 22562,"id": 245},
{"nl": "haalbaar","art": null,"de": "machbar, erreichbar","pos": "bn","cloze": "Is die deadline nog {haalbaar}?","rank": 22757,"id": 246},
{"nl": "samenvatten","art": null,"de": "zusammenfassen","pos": "ww","cloze": "Kun je het kort {samenvatten}?","rank": 23168,"id": 247},
{"nl": "hardnekkig","art": null,"de": "hartnäckig","pos": "bn","cloze": "Het is een {hardnekkig} misverstand.","rank": 23543,"id": 248},
{"nl": "opluchten","art": null,"de": "erleichtern","pos": "ww","cloze": "Dat nieuws {luchtte} me enorm {op}.","rank": 25000,"id": 249},
{"nl": "betwijfelen","art": null,"de": "bezweifeln","pos": "ww","cloze": "Ik {betwijfel} of dat gaat lukken.","rank": 25610,"id": 250},
{"nl": "neigen","art": null,"de": "neigen","pos": "ww","cloze": "Ik {neig} ernaar om het voorstel af te wijzen.","rank": 27754,"id": 251},
{"nl": "uitputten","art": null,"de": "erschöpfen","pos": "ww","cloze": "De reis had ons volledig {uitgeput}.","rank": 33396,"id": 252},
{"nl": "geenszins","art": null,"de": "keineswegs","pos": "bw","cloze": "Dat is {geenszins} mijn bedoeling.","rank": 34249,"id": 253},
{"nl": "tegenvallen","art": null,"de": "enttäuschen, schlechter ausfallen","pos": "ww","cloze": "Het weer {viel} behoorlijk {tegen}.","rank": 34670,"id": 254},
{"nl": "omslachtig","art": null,"de": "umständlich","pos": "bn","cloze": "Die procedure is veel te {omslachtig}.","rank": 45157,"id": 255}];

// Erfundene Wörter für die Einstufung (Kontrollitems gegen Selbstüberschätzung).
window.PSEUDO = ["verkwalmen", "ontstrepen", "bespoelken", "aftroelen", "inverzelen", "gehaarsel", "verhoedzaam", "kwelmatig", "onderstoemd", "bemoezelen", "verstriemen", "aanhoevelen", "ontvraaien", "verspalken", "neerkwelen", "verglaaien", "ondertreuzelen", "gestrompel", "verhaaldzaam", "opsnaveren", "betreuzelen", "verwoemen", "uitstrelken", "ontblaarsen"];
