// Amai — Wortliste. Ränge aus dem Dutch Crowdsourcing Project (Brysbaert, Keuleers,
// Mandera 2019, https://osf.io/5fk8d/): Position nach SUBTLEX-NL-Zipf unter den Wörtern
// mit prevalence_BE >= 1.4, also unter dem, was Flamen tatsächlich kennen.
// prevBE = Bekanntheit in Flandern (z, gesättigt bei 1.96). gap = BE minus NL:
// hohe Werte sind flämisch-spezifisch, negative eher niederländisch.
window.WORDS = [{"nl": "volgens","art": null,"de": "laut, gemäß","pos": "bw","cloze": "{Volgens} mij klopt dat niet.","rank": 281,"prevBE": 1.77,"gap": -0.11,"id": 0},
{"nl": "kans","art": "de","de": "die Chance, die Möglichkeit","pos": "zn","cloze": "De {kans} dat het lukt is klein.","rank": 313,"prevBE": 1.85,"gap": -0.06,"id": 1},
{"nl": "zorg","art": "de","de": "die Sorge","pos": "zn","cloze": "Dat is mijn grootste {zorg}.","rank": 354,"prevBE": 1.84,"gap": -0.07,"id": 2},
{"nl": "meteen","art": null,"de": "sofort","pos": "bw","cloze": "Ik kom er {meteen} aan.","rank": 355,"prevBE": 1.81,"gap": -0.06,"id": 3},
{"nl": "druk","art": "de","de": "der Druck","pos": "zn","cloze": "Ik voel veel {druk} op mijn werk.","rank": 372,"prevBE": 1.9,"gap": -0.01,"id": 4},
{"nl": "schuld","art": "de","de": "die Schuld","pos": "zn","cloze": "Het is niet jouw {schuld}.","rank": 419,"prevBE": 1.9,"gap": -0.02,"id": 5},
{"nl": "nogal","art": null,"de": "ziemlich","pos": "bw","cloze": "Dat was {nogal} onhandig.","rank": 499,"prevBE": 1.75,"gap": -0.17,"id": 6},
{"nl": "onderzoek","art": "het","de": "die Untersuchung, die Forschung","pos": "zn","cloze": "Uit {onderzoek} blijkt dat het werkt.","rank": 575,"prevBE": 1.79,"gap": -0.17,"id": 7},
{"nl": "bewijs","art": "het","de": "der Beweis","pos": "zn","cloze": "Er is geen enkel {bewijs} voor die theorie.","rank": 613,"prevBE": 1.91,"gap": 0.03,"id": 8},
{"nl": "afspraak","art": "de","de": "die Verabredung, der Termin","pos": "zn","cloze": "Ik heb morgen een {afspraak} bij de tandarts.","rank": 630,"prevBE": 1.9,"gap": 0.03,"id": 9},
{"nl": "gevaar","art": "het","de": "die Gefahr","pos": "zn","cloze": "Er dreigt {gevaar} bij hoogwater.","rank": 666,"prevBE": 1.9,"gap": 0.03,"id": 10},
{"nl": "zodra","art": null,"de": "sobald","pos": "bw","cloze": "Ik bel je {zodra} ik thuis ben.","rank": 698,"prevBE": 1.72,"gap": -0.04,"id": 11},
{"nl": "missen","art": null,"de": "vermissen","pos": "ww","cloze": "Ik {mis} mijn oude buurt.","rank": 699,"prevBE": 1.85,"gap": -0.03,"id": 12},
{"nl": "wet","art": "de","de": "das Gesetz","pos": "zn","cloze": "De nieuwe {wet} gaat in januari in.","rank": 726,"prevBE": 1.74,"gap": 0.02,"id": 13},
{"nl": "ruimte","art": "de","de": "der Raum, der Platz","pos": "zn","cloze": "Er is nog {ruimte} voor verbetering.","rank": 747,"prevBE": 1.85,"gap": -0.11,"id": 14},
{"nl": "tenzij","art": null,"de": "es sei denn","pos": "bw","cloze": "We gaan door, {tenzij} het gaat onweren.","rank": 749,"prevBE": 1.96,"gap": 0.0,"id": 15},
{"nl": "bedrijf","art": "het","de": "das Unternehmen","pos": "zn","cloze": "Ze werkt bij een klein {bedrijf}.","rank": 768,"prevBE": 1.96,"gap": 0.08,"id": 16},
{"nl": "regelen","art": null,"de": "regeln, organisieren","pos": "ww","cloze": "Ik {regel} de tickets wel.","rank": 773,"prevBE": 1.84,"gap": -0.02,"id": 17},
{"nl": "haast","art": "de","de": "die Eile","pos": "zn","cloze": "Er is geen {haast} bij.","rank": 777,"prevBE": 1.9,"gap": 0.07,"id": 18},
{"nl": "moeite","art": "de","de": "die Mühe","pos": "zn","cloze": "Doe geen {moeite}, ik doe het zelf wel.","rank": 803,"prevBE": 1.96,"gap": 0.09,"id": 19},
{"nl": "lastig","art": null,"de": "schwierig, lästig","pos": "bn","cloze": "Dat wordt een {lastige} klus.","rank": 813,"prevBE": 1.9,"gap": -0.02,"id": 20},
{"nl": "keuze","art": "de","de": "die Wahl","pos": "zn","cloze": "Dat is een lastige {keuze}.","rank": 824,"prevBE": 1.85,"gap": -0.07,"id": 21},
{"nl": "bereiken","art": null,"de": "erreichen","pos": "ww","cloze": "We hebben ons doel bijna {bereikt}.","rank": 843,"prevBE": 1.89,"gap": 0.02,"id": 22},
{"nl": "blijkbaar","art": null,"de": "anscheinend","pos": "bw","cloze": "Hij is {blijkbaar} al vertrokken.","rank": 865,"prevBE": 1.9,"gap": 0.03,"id": 23},
{"nl": "uiteindelijk","art": null,"de": "schließlich, letztendlich","pos": "bw","cloze": "{Uiteindelijk} bleven we thuis.","rank": 896,"prevBE": 1.85,"gap": -0.06,"id": 24},
{"nl": "rekening","art": "de","de": "die Rechnung","pos": "zn","cloze": "Mag ik de {rekening}, alstublieft?","rank": 933,"prevBE": 1.69,"gap": -0.22,"id": 25},
{"nl": "kennis","art": "de","de": "das Wissen","pos": "zn","cloze": "Mijn {kennis} van het Nederlands wordt beter.","rank": 935,"prevBE": 1.9,"gap": 0.03,"id": 26},
{"nl": "verschil","art": "het","de": "der Unterschied","pos": "zn","cloze": "Het {verschil} is nauwelijks te zien.","rank": 956,"prevBE": 1.79,"gap": -0.09,"id": 27},
{"nl": "last","art": "de","de": "die Last","pos": "zn","cloze": "Ik heb {last} van mijn rug.","rank": 966,"prevBE": 1.85,"gap": -0.06,"id": 28},
{"nl": "indruk","art": "de","de": "der Eindruck","pos": "zn","cloze": "Ik had de {indruk} dat ze moe was.","rank": 1016,"prevBE": 1.81,"gap": -0.1,"id": 29},
{"nl": "bereid","art": null,"de": "bereit","pos": "bn","cloze": "Ik ben {bereid} om te helpen.","rank": 1053,"prevBE": 1.77,"gap": -0.1,"id": 30},
{"nl": "onmiddellijk","art": null,"de": "sofort","pos": "bw","cloze": "Ze reageerde {onmiddellijk}.","rank": 1055,"prevBE": 1.7,"gap": -0.06,"id": 31},
{"nl": "ervaring","art": "de","de": "die Erfahrung","pos": "zn","cloze": "Ze heeft jarenlange {ervaring} in de zorg.","rank": 1079,"prevBE": 1.85,"gap": -0.11,"id": 32},
{"nl": "richting","art": "de","de": "die Richtung","pos": "zn","cloze": "We liepen in de verkeerde {richting}.","rank": 1087,"prevBE": 1.76,"gap": -0.12,"id": 33},
{"nl": "toevallig","art": null,"de": "zufällig","pos": "bn","cloze": "Ik kwam haar {toevallig} tegen.","rank": 1089,"prevBE": 1.9,"gap": -0.01,"id": 34},
{"nl": "leeftijd","art": "de","de": "das Alter","pos": "zn","cloze": "Op die {leeftijd} leer je snel.","rank": 1123,"prevBE": 1.9,"gap": -0.06,"id": 35},
{"nl": "tevreden","art": null,"de": "zufrieden","pos": "bn","cloze": "Ik ben heel {tevreden} met het resultaat.","rank": 1165,"prevBE": 1.96,"gap": 0.09,"id": 36},
{"nl": "behoorlijk","art": null,"de": "ziemlich, ordentlich","pos": "bn","cloze": "Het was {behoorlijk} koud vanochtend.","rank": 1203,"prevBE": 1.9,"gap": -0.06,"id": 37},
{"nl": "gedrag","art": "het","de": "das Verhalten","pos": "zn","cloze": "Zijn {gedrag} was echt onacceptabel.","rank": 1238,"prevBE": 1.85,"gap": -0.11,"id": 38},
{"nl": "lukken","art": null,"de": "gelingen","pos": "ww","cloze": "Het is me eindelijk {gelukt}.","rank": 1245,"prevBE": 1.84,"gap": -0.07,"id": 39},
{"nl": "oplossing","art": "de","de": "die Lösung","pos": "zn","cloze": "Er is nog geen {oplossing} gevonden.","rank": 1300,"prevBE": 1.9,"gap": 0.03,"id": 40},
{"nl": "ruim","art": null,"de": "geräumig, reichlich","pos": "bn","cloze": "We hebben nog {ruim} de tijd.","rank": 1329,"prevBE": 1.9,"gap": -0.01,"id": 41},
{"nl": "voorkomen","art": null,"de": "verhindern","pos": "ww","cloze": "Zo kun je veel problemen {voorkomen}.","rank": 1334,"prevBE": 1.96,"gap": 0.04,"id": 42},
{"nl": "gedragen","art": null,"de": "sich benehmen","pos": "ww","cloze": "{Gedraag} je een beetje.","rank": 1351,"prevBE": 1.85,"gap": -0.11,"id": 43},
{"nl": "verbergen","art": null,"de": "verbergen","pos": "ww","cloze": "Ze kon haar teleurstelling niet {verbergen}.","rank": 1353,"prevBE": 1.9,"gap": 0.03,"id": 44},
{"nl": "verwachten","art": null,"de": "erwarten","pos": "ww","cloze": "Ik had er meer van {verwacht}.","rank": 1355,"prevBE": 1.76,"gap": -0.2,"id": 45},
{"nl": "mening","art": "de","de": "die Meinung","pos": "zn","cloze": "Naar mijn {mening} is dat te duur.","rank": 1360,"prevBE": 1.96,"gap": 0.09,"id": 46},
{"nl": "nauwelijks","art": null,"de": "kaum","pos": "bw","cloze": "Ik kon hem {nauwelijks} verstaan.","rank": 1395,"prevBE": 1.96,"gap": 0.1,"id": 47},
{"nl": "oplossen","art": null,"de": "lösen","pos": "ww","cloze": "We moeten dit probleem samen {oplossen}.","rank": 1403,"prevBE": 1.84,"gap": -0.12,"id": 48},
{"nl": "steun","art": "de","de": "die Unterstützung","pos": "zn","cloze": "Bedankt voor je {steun}.","rank": 1412,"prevBE": 1.9,"gap": 0.03,"id": 49},
{"nl": "vervelend","art": null,"de": "lästig, langweilig","pos": "bn","cloze": "Wat {vervelend} voor je.","rank": 1420,"prevBE": 1.9,"gap": 0.07,"id": 50},
{"nl": "belang","art": "het","de": "die Bedeutung, das Interesse","pos": "zn","cloze": "Het is van groot {belang} dat je op tijd komt.","rank": 1422,"prevBE": 1.96,"gap": 0.0,"id": 51},
{"nl": "ondanks","art": null,"de": "trotz","pos": "bw","cloze": "{Ondanks} de regen was het gezellig.","rank": 1440,"prevBE": 1.75,"gap": -0.16,"id": 52},
{"nl": "kwestie","art": "de","de": "die Angelegenheit, die Frage","pos": "zn","cloze": "Dat is een {kwestie} van smaak.","rank": 1463,"prevBE": 1.72,"gap": -0.01,"id": 53},
{"nl": "gewend","art": null,"de": "gewohnt","pos": "bn","cloze": "Ik ben dat niet {gewend}.","rank": 1465,"prevBE": 1.9,"gap": 0.02,"id": 54},
{"nl": "genieten","art": null,"de": "genießen","pos": "ww","cloze": "We hebben enorm {genoten} van de vakantie.","rank": 1473,"prevBE": 1.9,"gap": -0.01,"id": 55},
{"nl": "opgeven","art": null,"de": "aufgeben","pos": "ww","cloze": "Geef nooit te snel {op}.","rank": 1499,"prevBE": 1.89,"gap": -0.07,"id": 56},
{"nl": "toeval","art": "het","de": "der Zufall","pos": "zn","cloze": "Dat is puur {toeval}.","rank": 1501,"prevBE": 1.9,"gap": -0.01,"id": 57},
{"nl": "voorlopig","art": null,"de": "vorläufig","pos": "bn","cloze": "{Voorlopig} blijft alles zoals het is.","rank": 1554,"prevBE": 1.9,"gap": -0.06,"id": 58},
{"nl": "bovendien","art": null,"de": "außerdem","pos": "bw","cloze": "Het is duur, en {bovendien} lelijk.","rank": 1557,"prevBE": 1.9,"gap": 0.03,"id": 59},
{"nl": "verhuizen","art": null,"de": "umziehen","pos": "ww","cloze": "We {verhuizen} volgende maand naar Utrecht.","rank": 1567,"prevBE": 1.74,"gap": -0.12,"id": 60},
{"nl": "wellicht","art": null,"de": "vielleicht","pos": "bw","cloze": "{Wellicht} kunnen we het later bespreken.","rank": 1568,"prevBE": 1.75,"gap": -0.08,"id": 61},
{"nl": "toestand","art": "de","de": "der Zustand","pos": "zn","cloze": "De {toestand} van de patiënt is stabiel.","rank": 1571,"prevBE": 1.64,"gap": -0.19,"id": 62},
{"nl": "omgeving","art": "de","de": "die Umgebung","pos": "zn","cloze": "De {omgeving} is heel rustig.","rank": 1584,"prevBE": 1.9,"gap": -0.06,"id": 63},
{"nl": "aanbod","art": "het","de": "das Angebot","pos": "zn","cloze": "Het {aanbod} geldt tot het einde van de maand.","rank": 1634,"prevBE": 1.91,"gap": 0.04,"id": 64},
{"nl": "minstens","art": null,"de": "mindestens","pos": "bw","cloze": "Je moet {minstens} twee uur wachten.","rank": 1658,"prevBE": 1.9,"gap": -0.06,"id": 65},
{"nl": "toegeven","art": null,"de": "zugeben","pos": "ww","cloze": "Hij wilde niet {toegeven} dat hij fout zat.","rank": 1659,"prevBE": 1.85,"gap": -0.06,"id": 66},
{"nl": "redelijk","art": null,"de": "ziemlich, vernünftig","pos": "bn","cloze": "Het gaat {redelijk} goed.","rank": 1677,"prevBE": 1.75,"gap": -0.21,"id": 67},
{"nl": "waarde","art": "de","de": "der Wert","pos": "zn","cloze": "Dat heeft voor mij veel {waarde}.","rank": 1682,"prevBE": 1.96,"gap": 0.13,"id": 68},
{"nl": "amper","art": null,"de": "kaum","pos": "bw","cloze": "Ik heb {amper} geslapen.","rank": 1695,"prevBE": 1.85,"gap": -0.11,"id": 69},
{"nl": "bewaren","art": null,"de": "aufbewahren","pos": "ww","cloze": "{Bewaar} de kaassoorten in de koelkast.","rank": 1697,"prevBE": 1.96,"gap": 0.04,"id": 70},
{"nl": "verband","art": "het","de": "der Zusammenhang","pos": "zn","cloze": "Er is geen {verband} tussen die twee dingen.","rank": 1701,"prevBE": 1.85,"gap": -0.02,"id": 71},
{"nl": "wijze","art": "de","de": "die Art und Weise","pos": "zn","cloze": "Op welke {wijze} wilt u betalen?","rank": 1708,"prevBE": 1.72,"gap": -0.08,"id": 72},
{"nl": "uiteraard","art": null,"de": "selbstverständlich","pos": "bw","cloze": "Dat mag {uiteraard}.","rank": 1712,"prevBE": 1.9,"gap": 0.07,"id": 73},
{"nl": "zwijgen","art": null,"de": "schweigen","pos": "ww","cloze": "Ze bleef de hele avond {zwijgen}.","rank": 1726,"prevBE": 1.84,"gap": -0.03,"id": 74},
{"nl": "namelijk","art": null,"de": "nämlich","pos": "bw","cloze": "Ik kan niet komen; ik ben {namelijk} ziek.","rank": 1741,"prevBE": 1.81,"gap": -0.05,"id": 75},
{"nl": "onderwerp","art": "het","de": "das Thema","pos": "zn","cloze": "Laten we van {onderwerp} veranderen.","rank": 1756,"prevBE": 1.9,"gap": 0.04,"id": 76},
{"nl": "voldoende","art": null,"de": "ausreichend","pos": "bn","cloze": "Er is {voldoende} eten voor iedereen.","rank": 1769,"prevBE": 1.96,"gap": 0.0,"id": 77},
{"nl": "besef","art": "het","de": "das Bewusstsein","pos": "zn","cloze": "Het {besef} kwam pas veel later.","rank": 1776,"prevBE": 1.85,"gap": 0.19,"id": 78},
{"nl": "dringend","art": null,"de": "dringend","pos": "bn","cloze": "Ik moet je {dringend} spreken.","rank": 1802,"prevBE": 1.84,"gap": -0.07,"id": 79},
{"nl": "plotseling","art": null,"de": "plötzlich","pos": "bn","cloze": "{Plotseling} ging het licht uit.","rank": 1804,"prevBE": 1.96,"gap": 0.16,"id": 80},
{"nl": "poging","art": "de","de": "der Versuch","pos": "zn","cloze": "Bij de derde {poging} lukte het.","rank": 1831,"prevBE": 1.9,"gap": -0.06,"id": 81},
{"nl": "overtuigen","art": null,"de": "überzeugen","pos": "ww","cloze": "Zijn argumenten hebben me niet {overtuigd}.","rank": 1849,"prevBE": 1.9,"gap": -0.01,"id": 82},
{"nl": "storen","art": null,"de": "stören","pos": "ww","cloze": "Sorry dat ik {stoor}.","rank": 1861,"prevBE": 1.9,"gap": 0.03,"id": 83},
{"nl": "herkennen","art": null,"de": "wiedererkennen","pos": "ww","cloze": "Ik {herkende} haar stem meteen.","rank": 1891,"prevBE": 1.96,"gap": 0.05,"id": 84},
{"nl": "eisen","art": null,"de": "fordern, verlangen","pos": "ww","cloze": "De vakbond {eist} hogere lonen.","rank": 1916,"prevBE": 1.73,"gap": -0.11,"id": 85},
{"nl": "voordeel","art": "het","de": "der Vorteil","pos": "zn","cloze": "Dat heeft ook een groot {voordeel}.","rank": 1918,"prevBE": 1.9,"gap": -0.06,"id": 86},
{"nl": "invloed","art": "de","de": "der Einfluss","pos": "zn","cloze": "Zijn mening heeft veel {invloed} op de groep.","rank": 1928,"prevBE": 1.8,"gap": -0.01,"id": 87},
{"nl": "bezwaar","art": "het","de": "der Einwand","pos": "zn","cloze": "Heb je {bezwaar} als ik het raam opendoe?","rank": 1935,"prevBE": 1.9,"gap": 0.03,"id": 88},
{"nl": "geschikt","art": null,"de": "geeignet","pos": "bn","cloze": "Deze film is niet {geschikt} voor kinderen.","rank": 1952,"prevBE": 1.85,"gap": -0.11,"id": 89},
{"nl": "overheid","art": "de","de": "die Regierung, der Staat","pos": "zn","cloze": "De {overheid} betaalt een deel mee.","rank": 1954,"prevBE": 1.85,"gap": -0.11,"id": 90},
{"nl": "gevoelig","art": null,"de": "empfindlich, sensibel","pos": "bn","cloze": "Dat is een {gevoelig} onderwerp.","rank": 1958,"prevBE": 1.96,"gap": 0.04,"id": 91},
{"nl": "klagen","art": null,"de": "klagen, sich beschweren","pos": "ww","cloze": "Ze {klaagt} altijd over het weer.","rank": 1997,"prevBE": 1.8,"gap": -0.16,"id": 92},
{"nl": "kennelijk","art": null,"de": "offenbar","pos": "bw","cloze": "Ze had het {kennelijk} niet gelezen.","rank": 2018,"prevBE": 1.84,"gap": -0.08,"id": 93},
{"nl": "ontslaan","art": null,"de": "entlassen","pos": "ww","cloze": "Ze is vorige maand {ontslagen}.","rank": 2060,"prevBE": 1.96,"gap": 0.0,"id": 94},
{"nl": "gemak","art": "het","de": "die Bequemlichkeit, die Leichtigkeit","pos": "zn","cloze": "Hij deed het met veel {gemak}.","rank": 2114,"prevBE": 1.9,"gap": 0.06,"id": 95},
{"nl": "voortaan","art": null,"de": "künftig, von nun an","pos": "bw","cloze": "{Voortaan} doe ik het zelf.","rank": 2124,"prevBE": 1.8,"gap": -0.12,"id": 96},
{"nl": "telkens","art": null,"de": "jedes Mal","pos": "bw","cloze": "Hij vergeet het {telkens} weer.","rank": 2136,"prevBE": 1.96,"gap": 0.17,"id": 97},
{"nl": "dwingen","art": null,"de": "zwingen","pos": "ww","cloze": "Niemand kan je {dwingen} om te tekenen.","rank": 2138,"prevBE": 1.79,"gap": -0.04,"id": 98},
{"nl": "ingewikkeld","art": null,"de": "kompliziert","pos": "bn","cloze": "Dat is te {ingewikkeld} om nu uit te leggen.","rank": 2143,"prevBE": 1.9,"gap": -0.01,"id": 99},
{"nl": "verzinnen","art": null,"de": "sich ausdenken","pos": "ww","cloze": "Hij kan altijd wel een smoes {verzinnen}.","rank": 2208,"prevBE": 1.79,"gap": -0.12,"id": 100},
{"nl": "waarderen","art": null,"de": "schätzen, würdigen","pos": "ww","cloze": "Ik {waardeer} je eerlijkheid.","rank": 2218,"prevBE": 1.9,"gap": 0.03,"id": 101},
{"nl": "onderhandelen","art": null,"de": "verhandeln","pos": "ww","cloze": "We {onderhandelen} nog over de prijs.","rank": 2230,"prevBE": 1.8,"gap": -0.16,"id": 102},
{"nl": "daad","art": "de","de": "die Tat","pos": "zn","cloze": "Het was een moedige {daad}.","rank": 2232,"prevBE": 1.75,"gap": -0.21,"id": 103},
{"nl": "bewust","art": null,"de": "bewusst","pos": "bn","cloze": "Ik was me daar niet van {bewust}.","rank": 2235,"prevBE": 1.78,"gap": -0.18,"id": 104},
{"nl": "negeren","art": null,"de": "ignorieren","pos": "ww","cloze": "Hij {negeerde} mijn vraag volledig.","rank": 2257,"prevBE": 1.85,"gap": -0.07,"id": 105},
{"nl": "slagen","art": null,"de": "bestehen, gelingen","pos": "ww","cloze": "Ze is voor haar examen {geslaagd}.","rank": 2269,"prevBE": 1.96,"gap": 0.13,"id": 106},
{"nl": "weigeren","art": null,"de": "sich weigern, verweigern","pos": "ww","cloze": "Hij {weigerde} zijn excuses aan te bieden.","rank": 2271,"prevBE": 1.91,"gap": -0.01,"id": 107},
{"nl": "behoefte","art": "de","de": "das Bedürfnis","pos": "zn","cloze": "Er is grote {behoefte} aan betaalbare woningen.","rank": 2290,"prevBE": 1.84,"gap": 0.02,"id": 108},
{"nl": "opzet","art": "de","de": "die Absicht","pos": "zn","cloze": "Dat deed hij met {opzet}.","rank": 2309,"prevBE": 1.9,"gap": -0.02,"id": 109},
{"nl": "uitdaging","art": "de","de": "die Herausforderung","pos": "zn","cloze": "Dit project is een echte {uitdaging}.","rank": 2321,"prevBE": 1.96,"gap": 0.04,"id": 110},
{"nl": "verplicht","art": null,"de": "verpflichtet, Pflicht-","pos": "bn","cloze": "Een helm is hier {verplicht}.","rank": 2355,"prevBE": 1.85,"gap": -0.11,"id": 111},
{"nl": "veroorzaken","art": null,"de": "verursachen","pos": "ww","cloze": "De storm heeft veel schade {veroorzaakt}.","rank": 2383,"prevBE": 1.96,"gap": 0.18,"id": 112},
{"nl": "vooruitgang","art": "de","de": "der Fortschritt","pos": "zn","cloze": "Je maakt duidelijk {vooruitgang}.","rank": 2395,"prevBE": 1.8,"gap": -0.12,"id": 113},
{"nl": "bevestigen","art": null,"de": "bestätigen","pos": "ww","cloze": "Kunt u de afspraak per mail {bevestigen}?","rank": 2403,"prevBE": 1.84,"gap": 0.03,"id": 114},
{"nl": "benieuwd","art": null,"de": "gespannt, neugierig","pos": "bn","cloze": "Ik ben {benieuwd} wat ze ervan vindt.","rank": 2419,"prevBE": 1.96,"gap": 0.05,"id": 115},
{"nl": "vermogen","art": "het","de": "die Fähigkeit, das Vermögen","pos": "zn","cloze": "Ze heeft een groot {vermogen} om te luisteren.","rank": 2427,"prevBE": 1.9,"gap": 0.16,"id": 116},
{"nl": "wennen","art": null,"de": "sich gewöhnen","pos": "ww","cloze": "Je moet even {wennen} aan het toetsenbord.","rank": 2428,"prevBE": 1.74,"gap": -0.09,"id": 117},
{"nl": "gewoonte","art": "de","de": "die Gewohnheit","pos": "zn","cloze": "Het is een oude {gewoonte} van me.","rank": 2454,"prevBE": 1.96,"gap": 0.09,"id": 118},
{"nl": "middel","art": "het","de": "das Mittel","pos": "zn","cloze": "Dat is een effectief {middel} tegen jeuk.","rank": 2463,"prevBE": 1.96,"gap": 0.0,"id": 119},
{"nl": "verspillen","art": null,"de": "verschwenden","pos": "ww","cloze": "Laten we geen tijd {verspillen}.","rank": 2479,"prevBE": 1.91,"gap": -0.01,"id": 120},
{"nl": "herhalen","art": null,"de": "wiederholen","pos": "ww","cloze": "Kun je dat nog een keer {herhalen}?","rank": 2502,"prevBE": 1.96,"gap": 0.05,"id": 121},
{"nl": "gebrek","art": "het","de": "der Mangel","pos": "zn","cloze": "Door {gebrek} aan tijd is het niet gelukt.","rank": 2506,"prevBE": 1.9,"gap": 0.07,"id": 122},
{"nl": "begrip","art": "het","de": "das Verständnis","pos": "zn","cloze": "Dank je voor je {begrip}.","rank": 2509,"prevBE": 1.9,"gap": 0.15,"id": 123},
{"nl": "afspreken","art": null,"de": "vereinbaren, ausmachen","pos": "ww","cloze": "Zullen we iets {afspreken} voor volgende week?","rank": 2539,"prevBE": 1.96,"gap": 0.09,"id": 124},
{"nl": "beschikbaar","art": null,"de": "verfügbar","pos": "bn","cloze": "Het rapport is nu online {beschikbaar}.","rank": 2546,"prevBE": 1.9,"gap": -0.02,"id": 125},
{"nl": "zeuren","art": null,"de": "nörgeln, quengeln","pos": "ww","cloze": "Hou eens op met {zeuren}.","rank": 2578,"prevBE": 1.81,"gap": -0.07,"id": 126},
{"nl": "verantwoordelijkheid","art": "de","de": "die Verantwortung","pos": "zn","cloze": "Hij neemt zijn {verantwoordelijkheid} serieus.","rank": 2601,"prevBE": null,"gap": null,"id": 127},
{"nl": "oorzaak","art": "de","de": "die Ursache","pos": "zn","cloze": "De {oorzaak} van de brand is nog onbekend.","rank": 2601,"prevBE": 1.96,"gap": 0.04,"id": 128},
{"nl": "achtergrond","art": "de","de": "der Hintergrund","pos": "zn","cloze": "Wat is jouw {achtergrond} qua opleiding?","rank": 2612,"prevBE": 1.96,"gap": 0.04,"id": 129},
{"nl": "ontkennen","art": null,"de": "leugnen, abstreiten","pos": "ww","cloze": "Hij blijft alles {ontkennen}.","rank": 2657,"prevBE": 1.8,"gap": -0.16,"id": 130},
{"nl": "ervaren","art": null,"de": "erfahren, erleben","pos": "ww","cloze": "Ik heb dat zelf ook zo {ervaren}.","rank": 2662,"prevBE": 1.9,"gap": -0.06,"id": 131},
{"nl": "verrassen","art": null,"de": "überraschen","pos": "ww","cloze": "Dat antwoord {verraste} me.","rank": 2730,"prevBE": 1.9,"gap": 0.13,"id": 132},
{"nl": "eis","art": "de","de": "die Forderung","pos": "zn","cloze": "Aan die {eis} kunnen we niet voldoen.","rank": 2767,"prevBE": 1.72,"gap": -0.08,"id": 133},
{"nl": "nuttig","art": null,"de": "nützlich","pos": "bn","cloze": "Dat was een {nuttige} tip.","rank": 2785,"prevBE": 1.72,"gap": -0.24,"id": 134},
{"nl": "stiekem","art": null,"de": "heimlich","pos": "bw","cloze": "Hij keek {stiekem} op zijn telefoon.","rank": 2833,"prevBE": 1.9,"gap": 0.08,"id": 135},
{"nl": "vermoeden","art": null,"de": "vermuten","pos": "ww","cloze": "Ik {vermoed} dat ze het al weet.","rank": 2860,"prevBE": 1.9,"gap": -0.01,"id": 136},
{"nl": "ontstaan","art": null,"de": "entstehen","pos": "ww","cloze": "Hoe is die gewoonte eigenlijk {ontstaan}?","rank": 2888,"prevBE": 1.8,"gap": 0.03,"id": 137},
{"nl": "belasting","art": "de","de": "die Steuer","pos": "zn","cloze": "Over dat inkomen betaal je {belasting}.","rank": 2892,"prevBE": 1.9,"gap": -0.02,"id": 138},
{"nl": "vermijden","art": null,"de": "vermeiden","pos": "ww","cloze": "Probeer de spits te {vermijden}.","rank": 2937,"prevBE": 1.96,"gap": 0.09,"id": 139},
{"nl": "klacht","art": "de","de": "die Beschwerde","pos": "zn","cloze": "Er zijn veel {klachten} binnengekomen.","rank": 2941,"prevBE": 1.9,"gap": -0.06,"id": 140},
{"nl": "noodzakelijk","art": null,"de": "notwendig","pos": "bn","cloze": "Een visum is niet {noodzakelijk}.","rank": 3031,"prevBE": 1.75,"gap": -0.17,"id": 141},
{"nl": "doorstaan","art": null,"de": "überstehen, durchstehen","pos": "ww","cloze": "De brug heeft de storm goed {doorstaan}.","rank": 3056,"prevBE": 1.9,"gap": 0.03,"id": 142},
{"nl": "afnemen","art": null,"de": "abnehmen","pos": "ww","cloze": "De belangstelling {neemt} langzaam {af}.","rank": 3069,"prevBE": 1.9,"gap": -0.06,"id": 143},
{"nl": "beweren","art": null,"de": "behaupten","pos": "ww","cloze": "Hij {beweert} dat hij van niets wist.","rank": 3074,"prevBE": 1.9,"gap": -0.06,"id": 144},
{"nl": "voorwaarde","art": "de","de": "die Bedingung","pos": "zn","cloze": "Ik doe het, op één {voorwaarde}.","rank": 3081,"prevBE": 1.81,"gap": -0.02,"id": 145},
{"nl": "afhankelijk","art": null,"de": "abhängig","pos": "bn","cloze": "Dat is {afhankelijk} van het weer.","rank": 3082,"prevBE": 1.75,"gap": -0.04,"id": 146},
{"nl": "bevolking","art": "de","de": "die Bevölkerung","pos": "zn","cloze": "De {bevolking} van de stad groeit snel.","rank": 3084,"prevBE": 1.9,"gap": -0.01,"id": 147},
{"nl": "beseffen","art": null,"de": "begreifen, sich bewusst werden","pos": "ww","cloze": "Ik {besefte} pas later hoe erg het was.","rank": 3109,"prevBE": 1.96,"gap": 0.17,"id": 148},
{"nl": "zeldzaam","art": null,"de": "selten","pos": "bn","cloze": "Die vogel is heel {zeldzaam} geworden.","rank": 3112,"prevBE": 1.68,"gap": -0.23,"id": 149},
{"nl": "aanvaarden","art": null,"de": "annehmen, akzeptieren","pos": "ww","cloze": "Ze heeft de baan uiteindelijk {aanvaard}.","rank": 3138,"prevBE": 1.76,"gap": -0.07,"id": 150},
{"nl": "verwerken","art": null,"de": "verarbeiten","pos": "ww","cloze": "Ze moet het nieuws nog {verwerken}.","rank": 3264,"prevBE": 1.8,"gap": -0.16,"id": 151},
{"nl": "schatten","art": null,"de": "schätzen","pos": "ww","cloze": "Ik {schat} hem op een jaar of veertig.","rank": 3268,"prevBE": 1.89,"gap": 0.03,"id": 152},
{"nl": "regelmatig","art": null,"de": "regelmäßig","pos": "bn","cloze": "Ik ga {regelmatig} zwemmen.","rank": 3296,"prevBE": 1.8,"gap": -0.12,"id": 153},
{"nl": "althans","art": null,"de": "zumindest","pos": "bw","cloze": "Hij komt, {althans} dat zei hij.","rank": 3348,"prevBE": 1.54,"gap": -0.25,"id": 154},
{"nl": "betrouwbaar","art": null,"de": "zuverlässig","pos": "bn","cloze": "Is die bron wel {betrouwbaar}?","rank": 3393,"prevBE": 1.96,"gap": 0.0,"id": 155},
{"nl": "grondig","art": null,"de": "gründlich","pos": "bn","cloze": "We hebben alles {grondig} gecontroleerd.","rank": 3405,"prevBE": 1.9,"gap": -0.01,"id": 156},
{"nl": "uitzondering","art": "de","de": "die Ausnahme","pos": "zn","cloze": "Er is één belangrijke {uitzondering}.","rank": 3469,"prevBE": 1.96,"gap": 0.16,"id": 157},
{"nl": "overwegen","art": null,"de": "erwägen, in Betracht ziehen","pos": "ww","cloze": "Ik {overweeg} om te verhuizen.","rank": 3483,"prevBE": 1.84,"gap": -0.12,"id": 158},
{"nl": "samenleving","art": "de","de": "die Gesellschaft","pos": "zn","cloze": "De {samenleving} verandert snel.","rank": 3542,"prevBE": 1.85,"gap": -0.11,"id": 159},
{"nl": "aanpak","art": "de","de": "die Herangehensweise, der Ansatz","pos": "zn","cloze": "Ik ben het niet eens met deze {aanpak}.","rank": 3554,"prevBE": 1.89,"gap": -0.07,"id": 160},
{"nl": "ondergaan","art": null,"de": "über sich ergehen lassen","pos": "ww","cloze": "Ze moest een zware operatie {ondergaan}.","rank": 3617,"prevBE": 1.89,"gap": -0.07,"id": 161},
{"nl": "onverwacht","art": null,"de": "unerwartet","pos": "bn","cloze": "Het bezoek kwam volledig {onverwacht}.","rank": 3648,"prevBE": 1.9,"gap": 0.03,"id": 162},
{"nl": "sfeer","art": "de","de": "die Stimmung, die Atmosphäre","pos": "zn","cloze": "Er hing een gespannen {sfeer}.","rank": 3702,"prevBE": 1.85,"gap": -0.03,"id": 163},
{"nl": "inmiddels","art": null,"de": "inzwischen","pos": "bw","cloze": "Ze woont hier {inmiddels} vijf jaar.","rank": 3761,"prevBE": 1.73,"gap": -0.07,"id": 164},
{"nl": "achterhalen","art": null,"de": "herausfinden, ermitteln","pos": "ww","cloze": "De politie probeert de dader te {achterhalen}.","rank": 3832,"prevBE": 1.9,"gap": 0.03,"id": 165},
{"nl": "gevolg","art": "het","de": "die Folge","pos": "zn","cloze": "Dat had grote {gevolgen} voor het bedrijf.","rank": 3868,"prevBE": 1.9,"gap": -0.02,"id": 166},
{"nl": "haasten","art": null,"de": "sich beeilen","pos": "ww","cloze": "Je hoeft je niet te {haasten}.","rank": 3932,"prevBE": 1.9,"gap": -0.06,"id": 167},
{"nl": "onderscheiden","art": null,"de": "unterscheiden","pos": "ww","cloze": "Je moet feiten van meningen {onderscheiden}.","rank": 3938,"prevBE": 1.83,"gap": -0.13,"id": 168},
{"nl": "somber","art": null,"de": "düster, trübe","pos": "bn","cloze": "Ze is de laatste tijd nogal {somber}.","rank": 3970,"prevBE": 1.84,"gap": -0.12,"id": 169},
{"nl": "beschouwen","art": null,"de": "betrachten, ansehen als","pos": "ww","cloze": "Ik {beschouw} hem als een goede vriend.","rank": 3994,"prevBE": 1.96,"gap": 0.04,"id": 170},
{"nl": "overdrijven","art": null,"de": "übertreiben","pos": "ww","cloze": "Nu {overdrijf} je echt.","rank": 4058,"prevBE": 1.9,"gap": -0.02,"id": 171},
{"nl": "ondernemen","art": null,"de": "unternehmen","pos": "ww","cloze": "Er moet snel actie worden {ondernomen}.","rank": 4107,"prevBE": 1.96,"gap": 0.16,"id": 172},
{"nl": "destijds","art": null,"de": "damals","pos": "bw","cloze": "Dat was {destijds} heel normaal.","rank": 4121,"prevBE": 1.81,"gap": 0.04,"id": 173},
{"nl": "blijken","art": null,"de": "sich herausstellen","pos": "ww","cloze": "Het {bleek} achteraf een misverstand te zijn.","rank": 4156,"prevBE": 1.7,"gap": -0.22,"id": 174},
{"nl": "bijdrage","art": "de","de": "der Beitrag","pos": "zn","cloze": "Bedankt voor je waardevolle {bijdrage}.","rank": 4201,"prevBE": 1.96,"gap": 0.12,"id": 175},
{"nl": "uitstellen","art": null,"de": "aufschieben, verschieben","pos": "ww","cloze": "Kunnen we de vergadering {uitstellen}?","rank": 4213,"prevBE": 1.9,"gap": 0.02,"id": 176},
{"nl": "vrijwel","art": null,"de": "so gut wie, nahezu","pos": "bw","cloze": "Het is {vrijwel} onmogelijk.","rank": 4271,"prevBE": 1.8,"gap": -0.04,"id": 177},
{"nl": "voorheen","art": null,"de": "früher, vormals","pos": "bw","cloze": "Dit heette {voorheen} anders.","rank": 4296,"prevBE": 1.75,"gap": 0.01,"id": 178},
{"nl": "verwachting","art": "de","de": "die Erwartung","pos": "zn","cloze": "Het resultaat overtrof onze {verwachtingen}.","rank": 4378,"prevBE": 1.73,"gap": -0.18,"id": 179},
{"nl": "tamelijk","art": null,"de": "ziemlich","pos": "bw","cloze": "Het is een {tamelijk} lang boek.","rank": 4494,"prevBE": 1.75,"gap": -0.03,"id": 180},
{"nl": "uitgebreid","art": null,"de": "ausführlich, umfangreich","pos": "bn","cloze": "Hij gaf een {uitgebreide} uitleg.","rank": 4625,"prevBE": 1.85,"gap": -0.11,"id": 181},
{"nl": "overleg","art": "het","de": "die Absprache, die Beratung","pos": "zn","cloze": "Na {overleg} met mijn collega's besloot ik te blijven.","rank": 4634,"prevBE": 1.96,"gap": 0.13,"id": 182},
{"nl": "deels","art": null,"de": "teilweise","pos": "bw","cloze": "Dat klopt {deels}.","rank": 4658,"prevBE": 1.9,"gap": 0.06,"id": 183},
{"nl": "overigens","art": null,"de": "übrigens","pos": "bw","cloze": "{Overigens} heb ik dat nooit gezegd.","rank": 4694,"prevBE": 1.62,"gap": -0.25,"id": 184},
{"nl": "enigszins","art": null,"de": "einigermaßen","pos": "bw","cloze": "Ik ben {enigszins} verbaasd.","rank": 4703,"prevBE": 1.65,"gap": -0.09,"id": 185},
{"nl": "vanzelfsprekend","art": null,"de": "selbstverständlich","pos": "bn","cloze": "Dat is helemaal niet {vanzelfsprekend}.","rank": 4877,"prevBE": 1.96,"gap": 0.17,"id": 186},
{"nl": "alsnog","art": null,"de": "doch noch","pos": "bw","cloze": "Het is {alsnog} gelukt.","rank": 4963,"prevBE": 1.48,"gap": -0.14,"id": 187},
{"nl": "begrijpelijk","art": null,"de": "verständlich","pos": "bn","cloze": "Je reactie is heel {begrijpelijk}.","rank": 5041,"prevBE": 1.86,"gap": 0.02,"id": 188},
{"nl": "zorgvuldig","art": null,"de": "sorgfältig","pos": "bn","cloze": "Lees de voorwaarden {zorgvuldig} door.","rank": 5155,"prevBE": 1.89,"gap": -0.02,"id": 189},
{"nl": "handhaven","art": null,"de": "aufrechterhalten, durchsetzen","pos": "ww","cloze": "De gemeente wil de regels strenger {handhaven}.","rank": 5211,"prevBE": 1.77,"gap": -0.01,"id": 190},
{"nl": "ontbreken","art": null,"de": "fehlen","pos": "ww","cloze": "Er {ontbreekt} nog een handtekening.","rank": 5241,"prevBE": 1.79,"gap": -0.07,"id": 191},
{"nl": "nauwkeurig","art": null,"de": "genau, präzise","pos": "bn","cloze": "Meet het zo {nauwkeurig} mogelijk.","rank": 5248,"prevBE": 1.8,"gap": -0.16,"id": 192},
{"nl": "overbodig","art": null,"de": "überflüssig","pos": "bn","cloze": "Die stap is eigenlijk {overbodig}.","rank": 5328,"prevBE": 1.85,"gap": -0.11,"id": 193},
{"nl": "opvallen","art": null,"de": "auffallen","pos": "ww","cloze": "Het {viel} me {op} dat hij stiller was dan anders.","rank": 5375,"prevBE": 1.91,"gap": 0.04,"id": 194},
{"nl": "tevens","art": null,"de": "zugleich, außerdem","pos": "bw","cloze": "Hij is arts en {tevens} onderzoeker.","rank": 5391,"prevBE": 1.89,"gap": 0.06,"id": 195},
{"nl": "vergissen","art": null,"de": "sich irren","pos": "ww","cloze": "Ik heb me in hem {vergist}.","rank": 5621,"prevBE": 1.9,"gap": -0.01,"id": 196},
{"nl": "gunnen","art": null,"de": "gönnen","pos": "ww","cloze": "Ik {gun} het je van harte.","rank": 5675,"prevBE": 1.85,"gap": -0.02,"id": 197},
{"nl": "bijdragen","art": null,"de": "beitragen","pos": "ww","cloze": "Iedereen kan iets {bijdragen} aan het project.","rank": 5728,"prevBE": 1.96,"gap": 0.0,"id": 198},
{"nl": "hoogstens","art": null,"de": "höchstens","pos": "bw","cloze": "Het duurt {hoogstens} tien minuten.","rank": 5737,"prevBE": 1.64,"gap": -0.13,"id": 199},
{"nl": "inleveren","art": null,"de": "abgeben","pos": "ww","cloze": "Je moet het formulier vrijdag {inleveren}.","rank": 5776,"prevBE": 1.91,"gap": -0.0,"id": 200},
{"nl": "vaststellen","art": null,"de": "feststellen","pos": "ww","cloze": "De arts {stelde} een lichte ontsteking {vast}.","rank": 5833,"prevBE": 1.85,"gap": -0.07,"id": 201},
{"nl": "inspanning","art": "de","de": "die Anstrengung","pos": "zn","cloze": "Het kostte veel {inspanning}.","rank": 5870,"prevBE": 1.96,"gap": 0.0,"id": 202},
{"nl": "neiging","art": "de","de": "die Neigung","pos": "zn","cloze": "Ik heb de {neiging} om alles uit te stellen.","rank": 5886,"prevBE": 1.83,"gap": 0.0,"id": 203},
{"nl": "daarentegen","art": null,"de": "hingegen, dagegen","pos": "bw","cloze": "Zijn broer is {daarentegen} heel rustig.","rank": 5899,"prevBE": 1.68,"gap": 0.19,"id": 204},
{"nl": "mislukken","art": null,"de": "scheitern","pos": "ww","cloze": "Het eerste experiment is {mislukt}.","rank": 5924,"prevBE": 1.85,"gap": -0.01,"id": 205},
{"nl": "streven","art": null,"de": "streben","pos": "ww","cloze": "We {streven} naar een oplossing voor het einde van het jaar.","rank": 5953,"prevBE": 1.75,"gap": -0.16,"id": 206},
{"nl": "gebruikelijk","art": null,"de": "üblich","pos": "bn","cloze": "Dat is hier niet {gebruikelijk}.","rank": 5961,"prevBE": 1.9,"gap": -0.01,"id": 207},
{"nl": "nadeel","art": "het","de": "der Nachteil","pos": "zn","cloze": "Het enige {nadeel} is de prijs.","rank": 5973,"prevBE": 1.85,"gap": -0.02,"id": 208},
{"nl": "stelling","art": "de","de": "die These","pos": "zn","cloze": "Ik ben het niet eens met die {stelling}.","rank": 5983,"prevBE": 1.9,"gap": -0.06,"id": 209},
{"nl": "vaardigheid","art": "de","de": "die Fertigkeit","pos": "zn","cloze": "Dat is een {vaardigheid} die je kunt leren.","rank": 6091,"prevBE": 1.89,"gap": -0.07,"id": 210},
{"nl": "afwijzen","art": null,"de": "ablehnen","pos": "ww","cloze": "De bank heeft mijn aanvraag {afgewezen}.","rank": 6265,"prevBE": 1.9,"gap": 0.03,"id": 211},
{"nl": "merkwaardig","art": null,"de": "merkwürdig","pos": "bn","cloze": "Ik vond zijn reactie nogal {merkwaardig}.","rank": 6402,"prevBE": 1.85,"gap": -0.06,"id": 212},
{"nl": "eigenschap","art": "de","de": "die Eigenschaft","pos": "zn","cloze": "Geduld is een handige {eigenschap}.","rank": 6407,"prevBE": 1.9,"gap": 0.03,"id": 213},
{"nl": "aandringen","art": null,"de": "drängen, darauf bestehen","pos": "ww","cloze": "Hij bleef {aandringen} op een verklaring.","rank": 6635,"prevBE": 1.76,"gap": -0.15,"id": 214},
{"nl": "afkeer","art": "de","de": "die Abneigung","pos": "zn","cloze": "Ik heb een diepe {afkeer} van bureaucratie.","rank": 6640,"prevBE": 1.84,"gap": 0.13,"id": 215},
{"nl": "drempel","art": "de","de": "die Schwelle","pos": "zn","cloze": "De {drempel} om hulp te vragen is hoog.","rank": 6644,"prevBE": 1.8,"gap": -0.06,"id": 216},
{"nl": "grotendeels","art": null,"de": "größtenteils","pos": "bw","cloze": "Het werk is {grotendeels} klaar.","rank": 6700,"prevBE": 1.7,"gap": -0.18,"id": 217},
{"nl": "meevallen","art": null,"de": "besser ausfallen als erwartet","pos": "ww","cloze": "Gelukkig {viel} de rekening {mee}.","rank": 6872,"prevBE": 1.84,"gap": -0.02,"id": 218},
{"nl": "opvallend","art": null,"de": "auffällig","pos": "bn","cloze": "Het is {opvallend} hoe stil het is.","rank": 6886,"prevBE": 1.79,"gap": -0.17,"id": 219},
{"nl": "desondanks","art": null,"de": "dennoch, trotzdem","pos": "bw","cloze": "Het regende; {desondanks} gingen we op pad.","rank": 7053,"prevBE": 1.79,"gap": -0.01,"id": 220},
{"nl": "aarzelen","art": null,"de": "zögern","pos": "ww","cloze": "Ik {aarzelde} even voordat ik antwoordde.","rank": 7083,"prevBE": 1.85,"gap": -0.03,"id": 221},
{"nl": "opmerken","art": null,"de": "bemerken","pos": "ww","cloze": "Ze {merkte} droogjes {op} dat het al laat was.","rank": 7161,"prevBE": 1.96,"gap": 0.04,"id": 222},
{"nl": "aanzienlijk","art": null,"de": "beträchtlich, erheblich","pos": "bn","cloze": "De prijs is {aanzienlijk} gestegen.","rank": 7169,"prevBE": 1.85,"gap": 0.06,"id": 223},
{"nl": "aanmoedigen","art": null,"de": "ermutigen","pos": "ww","cloze": "Mijn ouders {moedigden} me altijd {aan} om door te zetten.","rank": 7219,"prevBE": 1.9,"gap": -0.01,"id": 224},
{"nl": "benadrukken","art": null,"de": "betonen","pos": "ww","cloze": "De arts {benadrukte} dat rust belangrijk is.","rank": 7492,"prevBE": 1.85,"gap": 0.11,"id": 225},
{"nl": "schaars","art": null,"de": "knapp, rar","pos": "bn","cloze": "Water werd steeds {schaarser}.","rank": 7534,"prevBE": 1.85,"gap": -0.11,"id": 226},
{"nl": "beschikken","art": null,"de": "verfügen über","pos": "ww","cloze": "Het huis {beschikt} over een grote tuin.","rank": 7577,"prevBE": 1.8,"gap": -0.12,"id": 227},
{"nl": "struikelen","art": null,"de": "stolpern","pos": "ww","cloze": "Ik {struikelde} over een losse stoeptegel.","rank": 7752,"prevBE": 1.9,"gap": -0.02,"id": 228},
{"nl": "nadruk","art": "de","de": "die Betonung","pos": "zn","cloze": "De {nadruk} ligt op de eerste lettergreep.","rank": 7775,"prevBE": 1.96,"gap": 0.09,"id": 229},
{"nl": "gemeenschappelijk","art": null,"de": "gemeinsam","pos": "bn","cloze": "We hebben een {gemeenschappelijk} doel.","rank": 8042,"prevBE": 1.84,"gap": -0.04,"id": 230},
{"nl": "mits","art": null,"de": "sofern, vorausgesetzt","pos": "bw","cloze": "Het kan, {mits} je op tijd reserveert.","rank": 8176,"prevBE": 1.54,"gap": -0.26,"id": 231},
{"nl": "nalaten","art": null,"de": "unterlassen","pos": "ww","cloze": "Hij kon niet {nalaten} er iets over te zeggen.","rank": 8192,"prevBE": 1.79,"gap": 0.11,"id": 232},
{"nl": "ergeren","art": null,"de": "sich ärgern","pos": "ww","cloze": "Ik {erger} me aan dat geluid.","rank": 8432,"prevBE": 1.9,"gap": 0.11,"id": 233},
{"nl": "geleidelijk","art": null,"de": "allmählich","pos": "bn","cloze": "Het gaat {geleidelijk} beter.","rank": 8915,"prevBE": 1.81,"gap": 0.04,"id": 234},
{"nl": "zinvol","art": null,"de": "sinnvoll","pos": "bn","cloze": "Is het wel {zinvol} om door te gaan?","rank": 9083,"prevBE": 1.84,"gap": -0.08,"id": 235},
{"nl": "opvatting","art": "de","de": "die Auffassung","pos": "zn","cloze": "Zijn {opvatting} is behoorlijk ouderwets.","rank": 9300,"prevBE": 1.96,"gap": 0.05,"id": 236},
{"nl": "weliswaar","art": null,"de": "zwar","pos": "bw","cloze": "Het is {weliswaar} laat, maar ik kom nog.","rank": 9439,"prevBE": 1.7,"gap": 0.02,"id": 237},
{"nl": "toename","art": "de","de": "die Zunahme","pos": "zn","cloze": "We zien een {toename} van het aantal aanvragen.","rank": 9443,"prevBE": 1.9,"gap": -0.01,"id": 238},
{"nl": "toenemen","art": null,"de": "zunehmen","pos": "ww","cloze": "Het aantal klachten is sterk {toegenomen}.","rank": 9460,"prevBE": 1.84,"gap": -0.07,"id": 239},
{"nl": "belemmeren","art": null,"de": "behindern","pos": "ww","cloze": "De regels {belemmeren} kleine bedrijven.","rank": 9520,"prevBE": 1.8,"gap": 0.0,"id": 240},
{"nl": "bewering","art": "de","de": "die Behauptung","pos": "zn","cloze": "Die {bewering} klopt niet.","rank": 9961,"prevBE": 1.8,"gap": -0.12,"id": 241},
{"nl": "haalbaar","art": null,"de": "machbar, erreichbar","pos": "bn","cloze": "Is die deadline nog {haalbaar}?","rank": 10037,"prevBE": 1.75,"gap": -0.16,"id": 242},
{"nl": "samenvatten","art": null,"de": "zusammenfassen","pos": "ww","cloze": "Kun je het kort {samenvatten}?","rank": 10266,"prevBE": 1.96,"gap": 0.09,"id": 243},
{"nl": "bevorderen","art": null,"de": "fördern","pos": "ww","cloze": "Sporten {bevordert} de gezondheid.","rank": 10437,"prevBE": 1.86,"gap": -0.06,"id": 244},
{"nl": "verduidelijken","art": null,"de": "verdeutlichen","pos": "ww","cloze": "Kun je dat punt nog even {verduidelijken}?","rank": 11130,"prevBE": 1.84,"gap": 0.04,"id": 245},
{"nl": "hardnekkig","art": null,"de": "hartnäckig","pos": "bn","cloze": "Het is een {hardnekkig} misverstand.","rank": 11378,"prevBE": 1.84,"gap": -0.07,"id": 246},
{"nl": "omstandigheid","art": "de","de": "der Umstand","pos": "zn","cloze": "Onder deze {omstandigheden} gaat het niet.","rank": 11487,"prevBE": 1.84,"gap": 0.08,"id": 247},
{"nl": "maatregel","art": "de","de": "die Maßnahme","pos": "zn","cloze": "De regering neemt strenge {maatregelen}.","rank": 12520,"prevBE": 1.9,"gap": -0.06,"id": 248},
{"nl": "tegenvallen","art": null,"de": "enttäuschen, schlechter ausfallen","pos": "ww","cloze": "Het weer {viel} behoorlijk {tegen}.","rank": 12835,"prevBE": 1.84,"gap": 0.01,"id": 249},
{"nl": "neigen","art": null,"de": "neigen","pos": "ww","cloze": "Ik {neig} ernaar om het voorstel af te wijzen.","rank": 13060,"prevBE": 1.4,"gap": -0.1,"id": 250},
{"nl": "betwijfelen","art": null,"de": "bezweifeln","pos": "ww","cloze": "Ik {betwijfel} of dat gaat lukken.","rank": 13513,"prevBE": 1.85,"gap": 0.04,"id": 251},
{"nl": "opluchten","art": null,"de": "erleichtern","pos": "ww","cloze": "Dat nieuws {luchtte} me enorm {op}.","rank": 14656,"prevBE": 1.63,"gap": 0.1,"id": 252},
{"nl": "uitputten","art": null,"de": "erschöpfen","pos": "ww","cloze": "De reis had ons volledig {uitgeput}.","rank": 15051,"prevBE": 1.8,"gap": -0.07,"id": 253},
{"nl": "geenszins","art": null,"de": "keineswegs","pos": "bw","cloze": "Dat is {geenszins} mijn bedoeling.","rank": 15076,"prevBE": 1.7,"gap": 0.17,"id": 254},
{"nl": "omslachtig","art": null,"de": "umständlich","pos": "bn","cloze": "Die procedure is veel te {omslachtig}.","rank": 18984,"prevBE": 1.73,"gap": -0.14,"id": 255}];

// Erfundene Wörter für die Einstufung (Kontrollitems gegen Selbstüberschätzung).
window.PSEUDO = ["verkwalmen", "ontstrepen", "bespoelken", "aftroelen", "inverzelen", "gehaarsel", "verhoedzaam", "kwelmatig", "onderstoemd", "bemoezelen", "verstriemen", "aanhoevelen", "ontvraaien", "verspalken", "neerkwelen", "verglaaien", "ondertreuzelen", "gestrompel", "verhaaldzaam", "opsnaveren", "betreuzelen", "verwoemen", "uitstrelken", "ontblaarsen"];
